/**
 * Copyright (c) 2026 CounselorReady, a subsidiary of Ga Integrated Therapeutic Perspectives, LLC.
 * All rights reserved. Proprietary and confidential.
 * Unauthorized copying or distribution is strictly prohibited.
 */
// server/src/routes/askPresenterRoutes.js
// =========================================================================
// Ask the Presenter — course-scoped Q&A
// =========================================================================
// POST /api/ask-presenter
// Body: { slug, question, passage? }
//
// Answers are generated by Claude Haiku (same model/client config as
// server/src/services/remediationInference.js), grounded ONLY in the
// target course's own section content — not general chat. If the answer
// isn't in the course, the model says so and names the closest section.
// Requires authentication (reuses the existing auth middleware).
// =========================================================================

import express from 'express';
import Anthropic from '@anthropic-ai/sdk';
import { protect as requireAuth } from '../middleware/auth.js';
import { Course } from '../models/InteractiveCourse.js';
import PresenterQuestion from '../models/PresenterQuestion.js';

const router = express.Router();

const MODEL = 'claude-haiku-4-5-20251001';
const MAX_QUESTIONS_PER_DAY = 20;
const ANSWER_WORD_CAP = 150;
const MAX_CONTEXT_CHARS = 40000; // generous cap so very long courses don't blow the context window

function stripHtml(html) {
  return (html || '').toString()
    .replace(/<[^>]+>/g, ' ')
    .replace(/&nbsp;/g, ' ')
    .replace(/\s+/g, ' ')
    .trim();
}

// In-memory per-user/course/day rate limiter — acceptable for v1 (single
// dyno). Upgrade path: swap this Map for a Redis or Mongo-backed counter
// (TTL'd doc keyed on userId+slug+date) once this runs on more than one
// instance, since this Map does not share state across dynos and resets
// on every deploy/restart.
const questionCounts = new Map();

function rateLimitKey(userId, slug) {
  const day = new Date().toISOString().slice(0, 10);
  return `${userId}:${slug}:${day}`;
}

function checkAndIncrementRateLimit(userId, slug) {
  const key = rateLimitKey(userId, slug);
  const count = questionCounts.get(key) || 0;
  if (count >= MAX_QUESTIONS_PER_DAY) return { allowed: false, remaining: 0 };
  questionCounts.set(key, count + 1);
  return { allowed: true, remaining: MAX_QUESTIONS_PER_DAY - (count + 1) };
}

// Concatenate section text content (HTML stripped) as context, labeled by
// section so the model can cite which one it drew from.
function buildCourseContext(course) {
  const sections = course.sections || [];
  const labeled = sections.map((s, i) => {
    const label = `Section ${i + 1}: ${s.title || 'Untitled'}`;
    const text = (s.contentBlocks || [])
      .map(b => stripHtml(b.content || b.textContent || b.question || ''))
      .filter(Boolean)
      .join(' ');
    return text ? `[${label}]\n${text}` : null;
  }).filter(Boolean);

  let context = labeled.join('\n\n');
  if (context.length > MAX_CONTEXT_CHARS) {
    context = context.slice(0, MAX_CONTEXT_CHARS) + '\n\n[...course content truncated for length...]';
  }
  return context;
}

function buildSystemPrompt(context) {
  return `You are "Ask the Presenter" for a CounselorReady continuing-education course.
Answer ONLY using the course content provided below — never from general knowledge.
If the answer is not in the provided content, say so plainly and suggest which section
comes closest to the topic. Always name the section your answer draws from (e.g.
"From Section 2: ..."). Keep the answer under ${ANSWER_WORD_CAP} words. Do not give
clinical advice beyond what the course content itself states.

COURSE CONTENT:
${context}`;
}

router.post('/', requireAuth, async (req, res) => {
  try {
    const { slug, question, passage } = req.body || {};
    if (!slug || !question || !question.trim()) {
      return res.status(400).json({ success: false, error: 'slug and question are required' });
    }

    const rateLimit = checkAndIncrementRateLimit(req.user._id.toString(), slug);
    if (!rateLimit.allowed) {
      return res.status(429).json({
        success: false,
        error: `You've reached the limit of ${MAX_QUESTIONS_PER_DAY} questions per day for this course.`,
        remaining: 0
      });
    }

    const course = await Course.findOne({ slug });
    if (!course) {
      return res.status(404).json({ success: false, error: 'Course not found' });
    }

    if (!process.env.ANTHROPIC_API_KEY) {
      return res.status(500).json({ success: false, error: 'ANTHROPIC_API_KEY is not set' });
    }

    const context = buildCourseContext(course);
    const userContent = passage
      ? `Highlighted passage: "${passage}"\n\nQuestion: ${question}`
      : `Question: ${question}`;

    const client = new Anthropic();
    const response = await client.messages.create({
      model: MODEL,
      max_tokens: 400,
      system: buildSystemPrompt(context),
      messages: [{ role: 'user', content: userContent }],
    });

    const textBlock = response.content.find(c => c.type === 'text');
    const answer = textBlock ? textBlock.text.trim() : '';

    const sectionMatch = answer.match(/Section (\d+)/i);
    const answeredFromSection = sectionMatch
      ? (course.sections?.[parseInt(sectionMatch[1], 10) - 1]?.title || `Section ${sectionMatch[1]}`)
      : '';

    // Content-intelligence loop: log the QUESTION only, never the answer.
    PresenterQuestion.create({
      question: question.trim(),
      slug,
      userId: req.user._id,
      answeredFromSection,
    }).catch(err => console.error('[ask-presenter] failed to log question:', err.message));

    res.json({ success: true, answer, answeredFromSection, remaining: rateLimit.remaining });
  } catch (err) {
    console.error('[ask-presenter] failed:', err);
    res.status(500).json({ success: false, error: "Couldn't reach the presenter — try again" });
  }
});

export default router;
