/**
 * Copyright (c) 2026 CounselorReady, a subsidiary of Ga Integrated Therapeutic Perspectives, LLC.
 * All rights reserved. Proprietary and confidential.
 *
 * Generates client/public/sitemap.xml from the live published-course catalog
 * plus the public marketing/legal pages.
 *
 * Usage:
 *   node tools/generate-sitemap.cjs
 *   API_BASE=https://api.counselorready.com SITE=https://counselorready.com node tools/generate-sitemap.cjs
 *
 * Only public, indexable URLs are included. Gated app pages (dashboard, settings,
 * credentials, admin-*, partner-*) and the API are intentionally excluded — they are
 * also covered by robots.txt Disallow + per-page <meta name="robots" content="noindex">.
 */
const fs = require('fs');
const path = require('path');

const SITE = (process.env.SITE || 'https://counselorready.com').replace(/\/$/, '');
const API_BASE = (process.env.API_BASE || 'https://api.counselorready.com').replace(/\/$/, '');
const OUT = path.join(__dirname, '..', 'client', 'public', 'sitemap.xml');
const TODAY = new Date().toISOString().split('T')[0];

// Public, indexable static pages → [loc, changefreq, priority]
const STATIC_PAGES = [
  ['/',                        'daily',   '1.0'],
  ['/courses',                 'daily',   '0.9'],
  ['/blog',                    'weekly',  '0.6'],
  ['/about',                   'monthly', '0.5'],
  ['/subscription',            'monthly', '0.7'],
  ['/register',                'monthly', '0.6'],
  ['/ada-accommodations',      'yearly',  '0.2'],
  ['/non-discrimination',      'yearly',  '0.2'],
  ['/complaint-resolution',    'yearly',  '0.2'],
  ['/privacy',                 'yearly',  '0.2'],
  ['/terms',                   'yearly',  '0.2'],
  ['/refund-policy',           'yearly',  '0.2'],
];

function xmlEscape(s) {
  return String(s).replace(/&/g, '&amp;').replace(/</g, '&lt;').replace(/>/g, '&gt;')
    .replace(/"/g, '&quot;').replace(/'/g, '&apos;');
}

function urlEntry(loc, changefreq, priority, lastmod) {
  return [
    '  <url>',
    `    <loc>${xmlEscape(SITE + loc)}</loc>`,
    `    <lastmod>${lastmod || TODAY}</lastmod>`,
    `    <changefreq>${changefreq}</changefreq>`,
    `    <priority>${priority}</priority>`,
    '  </url>',
  ].join('\n');
}

async function fetchCourses() {
  const url = `${API_BASE}/api/interactive-courses?limit=500`;
  const res = await fetch(url, { headers: { Accept: 'application/json' } });
  if (!res.ok) throw new Error(`Catalog fetch failed: ${res.status} ${res.statusText}`);
  const json = await res.json();
  const arr = Array.isArray(json) ? json : (json.data || json.courses || json.items || []);
  return arr
    .filter(c => c && c.slug && (c.status ? c.status === 'published' : true))
    .map(c => ({ slug: c.slug, lastmod: (c.updatedAt || c.publishedAt || '').split('T')[0] || TODAY }));
}

async function main() {
  let courses = [];
  try {
    courses = await fetchCourses();
    console.log(`Fetched ${courses.length} published courses from ${API_BASE}`);
  } catch (err) {
    console.error(`WARNING: ${err.message}`);
    console.error('Writing sitemap with static pages only. Re-run when the API is reachable.');
  }

  const entries = [];
  for (const [loc, cf, pr] of STATIC_PAGES) entries.push(urlEntry(loc, cf, pr));
  for (const c of courses) entries.push(urlEntry(`/courses/${c.slug}`, 'weekly', '0.8', c.lastmod));

  const xml = [
    '<?xml version="1.0" encoding="UTF-8"?>',
    '<!-- Generated by tools/generate-sitemap.cjs — do not edit by hand. Re-run to refresh. -->',
    '<urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">',
    entries.join('\n'),
    '</urlset>',
    '',
  ].join('\n');

  fs.writeFileSync(OUT, xml, 'utf8');
  console.log(`Wrote ${entries.length} URLs → ${path.relative(path.join(__dirname, '..'), OUT)}`);
}

main().catch(err => { console.error(err); process.exit(1); });
