#!/usr/bin/env bash
# install-hooks.sh — one-time setup for local pre-commit and commit-msg hooks.
#
# Wires tools/check-seed.cjs into .git/hooks/pre-commit so that any
# `git commit` touching a seed*.{js,cjs,mjs} file under server/src/scripts/
# is blocked locally if it bypasses the Mongoose pre-save hook.
#
# Usage (from the repo root):
#   bash tools/install-hooks.sh
#
# This is optional — the GitHub Actions workflow in .github/workflows/seed-quality.yml
# is the canonical gate. The local hook is a courtesy for devs running git CLI.
# Mobile / GitHub web edits skip this hook by design (it can't run there);
# they are caught by the workflow on push.

set -euo pipefail

REPO_ROOT="$(git rev-parse --show-toplevel)"
HOOK_PATH="$REPO_ROOT/.git/hooks/pre-commit"

cat > "$HOOK_PATH" <<'EOF'
#!/usr/bin/env bash
# Auto-generated by tools/install-hooks.sh — do not edit by hand.
node tools/check-seed.cjs --staged
EOF

chmod +x "$HOOK_PATH"
echo "installed pre-commit hook → $HOOK_PATH"
echo "test it:  touch server/src/scripts/seed_smoke.js && git add . && git commit -m test"

# ---------------------------------------------------------------------------
# commit-msg hook — strips Claude attribution footers (CLAUDE.md "Commit & PR
# Hygiene": never add Co-Authored-By lines or "Generated with Claude Code").
#
# Strips rather than blocks: Claude Code appends these automatically, so a hard
# reject just creates a retry loop. Human Signed-off-by / Co-authored-by lines
# are preserved — only Claude-specific trailers are removed.
#
# NOTE: this cannot stop GitHub's squash-merge from concatenating commit bodies.
# Set Settings → General → Pull Requests → Default commit message to
# "Pull request title and description" for that.
# ---------------------------------------------------------------------------
MSG_HOOK_PATH="$REPO_ROOT/.git/hooks/commit-msg"

cat > "$MSG_HOOK_PATH" <<'EOF'
#!/usr/bin/env bash
# Auto-generated by tools/install-hooks.sh — do not edit by hand.
set -uo pipefail

MSG_FILE="$1"
PATTERN='^[[:space:]]*(Co-authored-by:[[:space:]]*Claude([[:space:]]|<)|Claude-Session:|Generated with \[?Claude Code|🤖 Generated with)'

if ! grep -qiE "$PATTERN" "$MSG_FILE"; then
  exit 0
fi

REMOVED=$(grep -icE "$PATTERN" "$MSG_FILE")
TMP="$(mktemp)"

# drop the attribution trailers, then collapse any trailing blank lines
grep -ivE "$PATTERN" "$MSG_FILE" | awk '
  { lines[NR] = $0 }
  END {
    last = NR
    while (last > 0 && lines[last] ~ /^[[:space:]]*$/) last--
    for (i = 1; i <= last; i++) print lines[i]
  }
' > "$TMP"

mv "$TMP" "$MSG_FILE"
echo "commit-msg: stripped ${REMOVED} Claude attribution line(s) per CLAUDE.md"
exit 0
EOF

chmod +x "$MSG_HOOK_PATH"
echo "installed commit-msg hook  → $MSG_HOOK_PATH"
