#!/usr/bin/env bash
# install-hooks.sh — one-time setup for local pre-commit hook.
#
# Wires tools/check-seed.cjs into .git/hooks/pre-commit so that any
# `git commit` touching a seed*.{js,cjs,mjs} file under server/src/scripts/
# is blocked locally if it bypasses the Mongoose pre-save hook.
#
# Usage (from the repo root):
#   bash tools/install-hooks.sh
#
# This is optional — the GitHub Actions workflow in .github/workflows/seed-quality.yml
# is the canonical gate. The local hook is a courtesy for devs running git CLI.
# Mobile / GitHub web edits skip this hook by design (it can't run there);
# they are caught by the workflow on push.

set -euo pipefail

REPO_ROOT="$(git rev-parse --show-toplevel)"
HOOK_PATH="$REPO_ROOT/.git/hooks/pre-commit"

cat > "$HOOK_PATH" <<'EOF'
#!/usr/bin/env bash
# Auto-generated by tools/install-hooks.sh — do not edit by hand.
node tools/check-seed.cjs --staged
EOF

chmod +x "$HOOK_PATH"
echo "installed pre-commit hook → $HOOK_PATH"
echo "test it:  touch server/src/scripts/seed_smoke.js && git add . && git commit -m test"
