/**
 * topUpTierOneCE.js — adds one substantive learner-content block to each of five
 * complete courses that fall just under the 6,000-words/CE floor once references
 * are excluded. Loads each course via the canonical model and saves through it so
 * the wordCount pre-save hook recomputes from sections[]. Idempotent: re-running
 * skips courses that already contain the top-up block.
 *
 *   node src/scripts/topUpTierOneCE.js
 */
import mongoose from 'mongoose';
import { Course } from '../models/InteractiveCourse.js';
import { countCourseWords, requiredWordsFor } from '../utils/courseWordCount.js';
import 'dotenv/config';

const MARKER = 'ce-topup-2026-06';

const TOPUPS = {
  'trauma-informed-care-ptsd': {
    title: 'Sustaining Trauma-Informed Care: Organizational Factors and Clinician Wellbeing',
    content: `<h2>Sustaining Trauma-Informed Care: Organizational Factors and Clinician Wellbeing</h2>
<p>Trauma-informed care is frequently described as if it were solely a matter of individual clinical technique, but in practice it is sustained — or undermined — at the level of the organization and the clinician's own wellbeing. A clinician's capacity to provide steady, attuned, trauma-informed care depends on the conditions in which they work and on their own sustainability over time.</p>
<h3>Trauma-Informed Care as an Organizational Commitment</h3>
<p>The principles of trauma-informed care — safety, trustworthiness and transparency, peer support, collaboration, empowerment, and attention to cultural and historical context — apply not only to the clinical encounter but to the organization as a whole. A setting that espouses trauma-informed values while subjecting staff and clients to unpredictability, coercive policies, or environments that replicate the dynamics of trauma cannot deliver genuinely trauma-informed care. Organizational implementation involves aligning policies, the physical environment, intake and administrative practices, and staff training with trauma-informed principles, so that a client's experience is consistent from the first point of contact through every interaction. When the organization itself is not trauma-informed, individual clinicians are left to compensate for system-level failures, which is neither effective nor sustainable.</p>
<h3>Secondary Traumatic Stress and Vicarious Trauma</h3>
<p>Clinicians who work with trauma are exposed, through empathic engagement, to material that can affect them profoundly over time. Secondary traumatic stress refers to trauma-like symptoms a clinician may develop from this exposure; vicarious traumatization refers to the cumulative transformation of the clinician's own inner world and beliefs about safety, trust, and the world; and burnout refers to the emotional exhaustion and depletion that can accompany the work. These are recognized occupational realities for those who do this work well — precisely because doing it well requires genuine empathic engagement — and they are not signs of weakness or inadequacy.</p>
<h3>Protecting the Capacity to Help</h3>
<p>Because a depleted or vicariously traumatized clinician cannot provide the steady, attuned presence that trauma survivors need, attending to clinician wellbeing is not a luxury but a component of competent, ethical practice. Sustainable trauma work requires deliberate attention to one's own wellbeing: maintaining manageable caseloads and a varied mix of clinical work, using consultation and supervision not only for clinical guidance but for processing the emotional impact of the work, maintaining boundaries between professional and personal life, attending to one's own physical and emotional health, and recognizing and responding to early signs of secondary stress rather than pushing through them. Organizations share responsibility here, through reasonable caseloads, supportive supervision structures, and a culture that treats secondary stress as an expected occupational reality to be addressed rather than a private failing to be hidden.</p>
<h3>The Reciprocal Relationship</h3>
<p>Organizational health and clinician wellbeing are reciprocal: supportive, genuinely trauma-informed organizations protect clinicians from avoidable stress and sustain their capacity to help, while organizations that neglect these factors drive turnover, burnout, and the erosion of care quality. Clinicians and supervisors who understand this relationship can advocate for the organizational conditions that make sustained trauma-informed care possible, recognizing that the wellbeing of those who provide care is inseparable from the quality of care that clients receive.</p>
<h3>Measurement-Based Care and Tracking Outcomes</h3>
<p>Sustaining quality in trauma treatment is supported by measurement-based care — the routine use of validated measures to track symptoms and functioning over the course of treatment. Systematically monitoring trauma symptoms, distress, and progress toward goals allows the clinician and client to see whether treatment is working, to adjust the approach when it is not, and to recognize and celebrate genuine improvement. Measurement-based care also supports the phase-based principle, helping the clinician gauge a client's stabilization and readiness, and it counters the drift and stagnation that can occur when progress is assessed only by impression. Used collaboratively and transparently, with measures shared and discussed with the client rather than imposed, this practice strengthens both accountability and the therapeutic alliance.</p>
<h3>Cultural Humility in Trauma-Informed Care</h3>
<p>Trauma is shaped by culture, history, and identity, and genuinely trauma-informed care is culturally responsive. The trauma-informed principle of attending to cultural, historical, and gender context recognizes that experiences of trauma, the meanings attached to them, the ways distress is expressed, and the supports a person can draw on all vary across cultures and communities, and that historical and intergenerational trauma shape many clients' experiences. Cultural humility — approaching each client as the expert on their own context, remaining curious rather than assuming, and attending to the intersecting identities and histories a client carries — is therefore inseparable from competent trauma-informed practice. A clinician who applies trauma-informed principles without cultural humility risks misunderstanding a client's experience and inadvertently replicating, rather than countering, the dynamics of marginalization.</p>

<h3>Avoiding Re-Traumatization Within the System of Care</h3>
<p>A core aim of trauma-informed care is to ensure that the systems meant to help do not themselves re-traumatize the people they serve. Medical, legal, social-service, and even mental health systems can inadvertently replicate the dynamics of the original trauma — stripping people of choice and control, requiring repeated retelling of painful events, responding with disbelief or blame, or conducting necessary procedures without explanation or consent. Each of these can echo the powerlessness of trauma and deepen harm at the moment a person sought help. Trauma-informed care prevents this by consistently restoring choice and control, minimizing unnecessary retelling, explaining procedures and seeking genuine consent, responding with respect and belief, and organizing services around the needs of those served. Because a person's experience of help-seeking is shaped by every point of contact — from the first phone call and the waiting room to administrative interactions and the clinical encounter itself — trauma-informed care attends to the whole system rather than the therapy hour alone, and clinicians can advocate within their organizations for the practices that make the entire system safer.</p>
`,
  },
  'instructional-design-for-mental-health-professionals': {
    title: 'Universal Design for Learning and Accessibility in Mental Health Training',
    content: `<h2>Universal Design for Learning and Accessibility in Mental Health Training</h2>
<p>Effective instructional design for mental health professionals must account for the diversity of learners who will engage with the material, and the framework of Universal Design for Learning (UDL) offers a principled approach to building training that is accessible and effective for a wide range of learners from the outset, rather than retrofitting accommodations after the fact.</p>
<h3>The Logic of Universal Design</h3>
<p>Universal Design for Learning rests on the recognition that learners vary — in background knowledge, in how they best take in information, in how they demonstrate understanding, and in what engages and motivates them — and that designing for this variability from the start produces better learning for everyone, not only for those who would otherwise require accommodation. Rather than assuming a single "average" learner and accommodating exceptions, UDL designs flexibility into the learning experience itself.</p>
<h3>The Three Principles</h3>
<p>UDL is organized around three principles. The first, providing multiple means of representation, recognizes that learners differ in how they perceive and comprehend information, and so offers content in multiple formats — text, visual, and where appropriate audio — with attention to clarity, structure, and the activation of background knowledge. The second, providing multiple means of action and expression, recognizes that learners differ in how they can demonstrate what they know, and so offers varied ways to engage with and respond to material rather than a single required format. The third, providing multiple means of engagement, recognizes that learners differ in what motivates and sustains their attention, and so attends to relevance, varied challenge, and the supports that help learners persist. Applied together, these principles produce training that reaches more learners more effectively.</p>
<h3>Accessibility as a Baseline</h3>
<p>Beyond the broader aims of UDL, accessibility is a baseline requirement: training materials should be usable by learners with disabilities, including those who use assistive technologies. This includes practical considerations such as readable text and adequate contrast, meaningful alternative text for images, captions and transcripts for audio and video content, clear and consistent structure and navigation, and content that does not rely on a single sensory channel to convey essential information. Designing for accessibility is both an ethical and, in many contexts, a legal obligation, and it benefits all learners — captions, clear structure, and multiple formats aid comprehension broadly, not only for those who require them.</p>
<h3>Application to Continuing Education</h3>
<p>For the design of continuing education for mental health professionals specifically, these principles translate into concrete choices: structuring content so learners can locate and revisit material easily, presenting key concepts in more than one way, offering varied opportunities for learners to check and apply their understanding, writing with clarity that does not sacrifice rigor, and ensuring materials are technically accessible. The result is training that respects the diversity of the professional audience and that maximizes the likelihood that learning translates into competent practice — the ultimate aim of any instructional design for clinicians.</p>
<h3>Aligning Objectives, Content, and Assessment</h3>
<p>A foundational principle of sound instructional design is alignment: the learning objectives, the instructional content, and the assessment must all point in the same direction. Objectives specify what learners should be able to do as a result of the training; content provides the knowledge and models the skills required to reach those objectives; and assessment measures whether the objectives have been met. When these three elements are aligned, learning is coherent and assessment is valid; when they drift apart — content that does not serve the stated objectives, or assessment that measures something other than what was taught — learning and evaluation both suffer. Designing backward from clear, measurable objectives, through aligned content, to assessment that genuinely tests those objectives, is among the most reliable ways to produce effective training.</p>
<h3>Evaluating Training Effectiveness</h3>
<p>Instructional design is not complete at delivery; evaluating whether training achieved its aims is essential to quality and improvement. Evaluation can attend to multiple levels: learners' reactions and satisfaction, what learners actually learned, whether learners apply the learning in practice, and the ultimate outcomes the training was meant to support. For continuing education for mental health professionals, the most meaningful evaluation reaches beyond satisfaction and even beyond knowledge gained to ask whether the training translates into changes in clinical practice and, ultimately, into better outcomes for clients. Building evaluation into the design from the outset — clarifying what success would look like and how it will be assessed — allows training to be refined over time and ensures that instructional effort genuinely serves professional competence rather than merely fulfilling a requirement.</p>

<h3>Adult Learning Principles and Engagement</h3>
<p>Instructional design for mental health professionals is design for adult learners, and it is most effective when grounded in how adults actually learn. Adult learners bring substantial experience and existing knowledge, are motivated by relevance to their real work and problems, value autonomy and self-direction, and learn best when new material connects to and builds on what they already know and can be applied to their practice. Effective design honors these principles: it makes the relevance to clinical practice explicit, draws on and respects learners' existing expertise, offers meaningful opportunities to apply and practice rather than only to absorb, and treats learners as capable professionals rather than passive recipients. Engagement is sustained not by entertainment but by genuine relevance, appropriate challenge, opportunities for active application, and respect for the learner's professional context. Training designed with these principles in mind is more likely to be completed, retained, and — most importantly — translated into improved clinical practice.</p>
`,
  },
  'unretiring-the-self-identity-purpose-depression-older-adults': {
    title: 'Purpose, Generativity, and Protective Factors in Later Life',
    content: `<h2>Purpose, Generativity, and Protective Factors in Later Life</h2>
<p>Alongside the genuine risks of depression and loss of identity that can accompany retirement and aging, clinical work with older adults attends to the protective factors — purpose, generativity, connection, and continued growth — that support wellbeing and resilience in later life. A purely deficit-focused view misses both the strengths older adults bring and the concrete sources of meaning that treatment can help cultivate.</p>
<h3>Purpose as a Protective Factor</h3>
<p>A sense of purpose — the experience of having goals, direction, and a reason to engage with life — is consistently associated with better mental and physical health in later life, including lower rates of depression and greater resilience in the face of loss and change. Retirement can threaten purpose when a person's sense of meaning has been bound up with their work role, but it also opens the possibility of new sources of purpose. Helping clients identify and cultivate what gives their life meaning beyond a former work role — relationships, contribution, learning, creativity, care for others, or engagement with values and community — is a central and hopeful focus of clinical work.</p>
<h3>Generativity and Contribution</h3>
<p>The concept of generativity — the desire and capacity to contribute to others and to future generations — captures a powerful source of meaning in later life. Older adults have much to offer: knowledge, experience, mentorship, care, and the perspective of a life lived. Opportunities to contribute, whether through family roles, mentoring, volunteering, creative work, or community engagement, support wellbeing and counter the isolation and sense of uselessness that ageist messages and role loss can produce. Clinical work can help clients recognize and act on their capacity for generativity, reframing later life as a stage with its own distinctive opportunities for contribution rather than only a series of losses.</p>
<h3>Connection and Social Engagement</h3>
<p>Social connection is among the most robust protective factors across the lifespan, and it carries particular weight in later life, when the losses of bereavement, retirement, and reduced mobility can erode a person's social world. Isolation and loneliness are significant risk factors for depression and for poor health outcomes in older adults, while maintained and cultivated connection is protective. Clinical work attends to the client's social world — supporting the maintenance and rebuilding of relationships, the development of new connections, and engagement with community — recognizing that connection is not merely pleasant but genuinely protective of mental and physical health.</p>
<h3>Continued Growth and a Strengths-Informed Stance</h3>
<p>A strengths-informed stance holds both the genuine difficulties of aging and the older adult's resilience, wisdom, and capacity for continued growth in view at once. Later life remains a period of development, adaptation, and the possibility of new learning, relationships, and meaning. Clinicians who approach older adults with this balanced perspective — neither minimizing real losses and risks nor reducing later life to decline — support clients in drawing on their strengths and in cultivating the purpose, generativity, and connection that make later life not merely endurable but genuinely meaningful. This orientation is itself therapeutic, countering the internalized ageism that can lead older adults to expect and accept diminishment.</p>
<h3>Identity Continuity and Reinvention</h3>
<p>Retirement poses a challenge to identity for those whose sense of self has been closely bound to their work and professional role, and clinical work attends to both the continuity and the reinvention of identity in this transition. Some clients benefit from recognizing the continuity of who they are beneath the change of role — the values, capacities, relationships, and qualities that persist regardless of employment. Others are supported by the possibility of reinvention — the discovery or development of new roles, interests, and sources of identity that retirement makes possible. Neither continuity nor reinvention is the single right path; the clinician helps each client navigate the renegotiation of identity in the way that fits their values and circumstances, framing retirement as a developmental transition with its own tasks rather than simply an ending.</p>
<h3>Screening for and Treating Late-Life Depression</h3>
<p>Depression in later life is common, frequently under-recognized, and highly treatable, yet it is too often dismissed as an inevitable part of aging or mistaken for other conditions. Depression in older adults may present differently than in younger people — sometimes with prominent physical complaints, cognitive difficulties, or irritability rather than overt sadness — which contributes to under-recognition. Routine screening, attention to the specific risk factors of later life (including bereavement, health changes, role loss, and isolation), and awareness that late-life depression is not a normal or acceptable part of aging all support identification. Treatment, including psychotherapy and, where appropriate, medication coordinated with medical providers, is effective for older adults, and the clinician approaches late-life depression with the same seriousness and therapeutic optimism as depression at any age, countering the ageism that would otherwise leave it untreated.</p>

<h3>Coordinating Care and Engaging Support Systems</h3>
<p>Effective work with older adults experiencing retirement-related distress and depression frequently involves more than individual therapy. Coordinating with medical providers is important, given the interplay of physical health, medication, and mood in later life, and given that depression can both affect and be affected by physical conditions. Engaging the older adult's support system — partners, family, and community — can strengthen treatment, reduce isolation, and mobilize the social connection that is so protective in later life, always with attention to the older adult's autonomy and consent regarding what is shared. The clinician also connects clients with community resources and opportunities for engagement, contribution, and connection that support purpose and counter isolation. This coordinated, systemic approach recognizes that an older adult's wellbeing is shaped by their health, relationships, and environment, and that supporting it frequently means working across these dimensions rather than within the therapy hour alone.</p>
`,
  },
  'the-long-goodbye-dementia-grief-family-systems': {
    title: 'Ambiguous Loss and Anticipatory Grief in Dementia Caregiving',
    content: `<h2>Ambiguous Loss and Anticipatory Grief in Dementia Caregiving</h2>
<p>The grief experienced by families of people with dementia has distinctive features that set it apart from conventional bereavement, and understanding the concepts of ambiguous loss and anticipatory grief is essential to supporting these families across the long trajectory of the illness.</p>
<h3>Ambiguous Loss</h3>
<p>Ambiguous loss, a concept developed by Pauline Boss, describes a loss that lacks the clarity and closure of death. In dementia, the person is physically present but progressively psychologically and relationally changed — present and absent at the same time. Family members grieve a person who is still alive, mourning the loss of the relationship, the shared history, and the person as they were, while continuing to care for the person as they are. This ambiguity is profoundly difficult: it lacks the social recognition, rituals, and clear endpoint that ordinarily support grieving, and it can leave family members feeling confused, guilty, and isolated in a grief that others may not recognize or validate. Naming ambiguous loss can itself be powerfully helpful, giving families a framework that makes sense of an experience they may have struggled to articulate.</p>
<h3>Anticipatory Grief</h3>
<p>Family members of people with dementia frequently experience anticipatory grief — grieving in advance of, and throughout, a prolonged decline. Rather than a single loss at the end, dementia involves a series of losses over time: the loss of capacities, of roles, of recognition, of the relationship as it was, each of which may be grieved as it occurs. This extended, recurring grief unfolds alongside the ongoing demands of caregiving, and it can be complicated by the guilt families may feel about grieving someone still alive or about their own exhaustion and ambivalence. Anticipatory grief is a normal response to a prolonged loss, not a failure of love or commitment.</p>
<h3>Grief, Guilt, and Ambivalence</h3>
<p>The grief of dementia caregiving is frequently entangled with guilt and ambivalence. Caregivers may feel guilt about negative feelings toward the person or the situation, about decisions such as placement in residential care, about respite or relief, or about wishing for an end to the suffering. They may hold genuinely contradictory feelings — love and resentment, devotion and exhaustion, hope and a wish for release — simultaneously. Normalizing these feelings as common and understandable responses to an extraordinarily difficult situation, rather than as evidence of inadequacy, relieves a significant source of suffering for caregivers who frequently judge themselves harshly.</p>
<h3>Supporting Families Across the Trajectory</h3>
<p>Clinical support attends to these distinctive features of dementia grief across the long course of the illness. This includes validating and normalizing ambiguous loss and anticipatory grief, helping families hold the contradictions of loving and grieving a person who is still present, supporting caregivers' own wellbeing and access to respite and support, and helping families find meaning and connection within the constraints of the illness. At the eventual death, families may experience a complex mixture of grief and relief, and may have already done much of their grieving — a pattern that deserves understanding rather than judgment. Throughout, the clinician supports the family system as a whole, recognizing that dementia reshapes relationships, roles, and the experience of loss for everyone involved.</p>
<h3>Family Systems and Shifting Roles</h3>
<p>Dementia reshapes the entire family system, not only the individual with the illness. Roles shift as a spouse becomes a caregiver, as adult children take on the care of a parent, and as long-standing family patterns are disrupted by the demands of the illness and by the losses it brings. These shifts can strain relationships, surface old conflicts, and create new ones — over caregiving responsibilities, financial and medical decisions, and differing perceptions of the person's condition and needs. A family-systems perspective helps the clinician understand and support the family as a whole, attending to how the illness redistributes roles and burdens, how decisions are made, and how the family communicates and supports — or fails to support — one another through a prolonged and demanding process.</p>
<h3>Caregiver Burden and Self-Care</h3>
<p>Dementia caregiving is among the most demanding of caregiving roles, frequently extending over many years and involving escalating physical, emotional, financial, and practical burdens. Caregivers are at elevated risk for depression, anxiety, health problems, and their own grief and exhaustion, and the chronic stress of caregiving can be severe. Supporting caregivers' own wellbeing is therefore not peripheral but central to clinical work with these families: this includes validating the difficulty of the role, addressing caregiver depression and stress, supporting access to respite and practical support, helping caregivers set sustainable limits, and countering the guilt that frequently prevents caregivers from attending to their own needs. A caregiver who is depleted cannot sustain care, and attending to the caregiver's wellbeing serves both the caregiver and the person with dementia.</p>

<h3>Meaning, Connection, and Care Through the Final Stages</h3>
<p>Even amid profound loss, families caring for a person with dementia can find meaning and maintain connection, and clinical support can help them do so. Connection in dementia frequently shifts from the verbal and cognitive toward the emotional and sensory — presence, touch, music, familiar routines, and shared moments that do not depend on memory or language. Helping families recognize and cultivate these forms of connection, and find meaning in the care they provide, can sustain them and preserve relationship even as the illness progresses. As the illness reaches its final stages and at the time of death, families may experience a complex mixture of grief, relief, and exhaustion, and may have already grieved much of their loss over the preceding years. The clinician supports families through this complicated bereavement without judgment, validating the full range of their feelings, and recognizing that the grief of dementia — extended, ambiguous, and entangled with caregiving — deserves the same compassion and support as any profound loss.</p>
`,
  },
  'seasoned-and-struggling-substance-use-disorders-older-adults': {
    title: 'Screening, Brief Intervention, and Referral for Older-Adult Substance Use',
    content: `<h2>Screening, Brief Intervention, and Referral for Older-Adult Substance Use</h2>
<p>Substance use disorders in older adults are frequently missed, and a systematic approach to identification and early intervention can make a substantial difference. The framework of screening, brief intervention, and referral to treatment offers a practical structure adaptable to the specific considerations of working with older adults.</p>
<h3>Why Older-Adult Substance Use Is Under-Identified</h3>
<p>Substance use in older adults is under-recognized for several reasons: clinicians frequently do not screen older patients, assuming substance use is a problem of younger people; the signs can be mistaken for other conditions of aging, such as cognitive changes, falls, or mood difficulties; generational stigma makes older adults less likely to disclose; and treatment systems designed around younger populations may not be experienced as appropriate. The result is that significant substance use — including the misuse of alcohol, prescription medications, and other substances — goes undetected and untreated in a population that is both vulnerable to harm and frequently responsive to intervention.</p>
<h3>Screening</h3>
<p>Routine, non-judgmental screening is the foundation. Screening older adults for substance use as a normal part of assessment — rather than only when problems are obvious — catches difficulties that would otherwise be missed, and screening tools adapted for or validated in older populations improve accuracy. Older adults are particularly vulnerable to harm at lower levels of use because of physiological changes in how the body processes substances, the high prevalence of medications that interact with alcohol and other substances, and the increased risk of falls, cognitive effects, and medical complications. Screening therefore attends not only to quantity but to the interaction of substances with health conditions and medications, and to the functional impact on the older adult's life.</p>
<h3>Brief Intervention</h3>
<p>For older adults whose use is risky but who do not require specialized treatment, brief intervention — a short, motivational, non-confrontational conversation about substance use and its effects — can be effective. Delivered with the empathic, autonomy-respecting spirit of motivational interviewing, brief intervention provides feedback, raises awareness of risks (including the specific risks of substances in the context of aging, health conditions, and medications), and supports the older adult's own motivation to change. The non-judgmental stance is especially important given the generational stigma that makes many older adults reluctant to discuss substance use.</p>
<h3>Referral to Treatment</h3>
<p>For older adults whose use warrants specialized care, referral to appropriate treatment is essential, and the referral is most effective when it accounts for the specific needs of older adults. This includes connecting clients with treatment that is age-appropriate and respectful, addressing practical barriers such as transportation and mobility, attending to co-occurring medical and mental health conditions, and recognizing that older adults frequently respond well to treatment when it is accessible and tailored to them. Throughout screening, brief intervention, and referral, the clinician maintains a respectful, non-stigmatizing stance that supports the older adult's dignity and autonomy, countering both the ageism that assumes older adults cannot change and the stigma that keeps substance use hidden.</p>
<h3>Prescription Medication Misuse and Polypharmacy</h3>
<p>Among older adults, substance-related risk frequently involves prescription medications and their interactions rather than only alcohol or illicit substances. Older adults are commonly prescribed multiple medications, and this polypharmacy creates risk for misuse, for dangerous interactions, and for harm even at prescribed doses when medications interact with one another, with alcohol, or with the physiological changes of aging. Medications with potential for misuse or dependence, including certain sedatives and pain medications, warrant particular attention. The clinician attends to the full medication picture, coordinates with prescribers and pharmacists, and recognizes that an older adult's difficulty may stem from the complex interaction of multiple prescribed substances rather than from a classic pattern of substance seeking — a picture that requires careful, non-judgmental assessment and coordinated medical management.</p>
<h3>Tailoring Treatment to Older Adults</h3>
<p>Treatment for substance use disorders is effective for older adults, and outcomes improve when treatment is tailored to their specific needs rather than delivered through programs designed for younger populations. Age-appropriate treatment attends to the pace and content that suit older learners, to co-occurring medical and cognitive conditions, to the losses and transitions that frequently accompany later-life substance use, and to the practical barriers of mobility, transportation, and access. A respectful, non-stigmatizing, and hopeful approach is essential, countering both the older adult's potential shame and the ageist assumption that older people cannot or need not change. With accessible, tailored, and respectful treatment, older adults frequently respond well, and addressing substance use can substantially improve their health, functioning, and quality of life.</p>

<h3>Co-Occurring Conditions and Late-Onset Use</h3>
<p>Substance use in older adults frequently co-occurs with depression, anxiety, grief, chronic pain, and cognitive changes, and these conditions interact in ways that shape both assessment and treatment. For some older adults, substance use is a long-standing pattern carried into later life; for others, it is late-onset, emerging in response to the losses, transitions, pain, and isolation of aging — bereavement, retirement, declining health, or loneliness. Late-onset use, in particular, is frequently connected to these life circumstances and to underlying depression or grief, and it may respond well to treatment that addresses the precipitating losses and co-occurring conditions alongside the substance use itself. Integrated treatment that addresses both the substance use and the co-occurring mental health conditions — understanding the substance use in the context of the distress it is being used to manage — is generally more effective than treating either in isolation, and it reflects the broader principle that older-adult substance use is best understood within the whole context of the person's life, health, and losses.</p>
`,
  },
};

const MONGODB_URI = process.env.MONGODB_URI;
if (!MONGODB_URI) { console.error('MONGODB_URI not set'); process.exit(1); }

async function main() {
  await mongoose.connect(MONGODB_URI);
  console.log('Connected.\n');
  for (const [slug, block] of Object.entries(TOPUPS)) {
    const doc = await Course.findOne({ slug });
    if (!doc) { console.log('SKIP (not found):', slug); continue; }
    const sections = doc.sections || [];
    if (!sections.length) { console.log('SKIP (no sections):', slug); continue; }
    const already = sections.some(s => (s.contentBlocks || []).some(b => b && (b.id === MARKER || b.title === block.title)));
    const before = countCourseWords(doc);
    const floor = requiredWordsFor(doc.ceHours);
    if (already) { console.log(`ALREADY DONE  ${doc.courseCode}  wordCount=${doc.wordCount}  count=${before}/${floor}`); continue; }
    const last = sections[sections.length - 1];
    last.contentBlocks = last.contentBlocks || [];
    const maxOrder = last.contentBlocks.reduce((m, b) => Math.max(m, (b && typeof b.order === 'number') ? b.order : 0), 0);
    last.contentBlocks.push({ id: MARKER, type: 'text', order: maxOrder + 1, title: block.title, content: block.content });
    doc.markModified('sections');
    await doc.save();
    const fresh = await Course.findById(doc._id);
    const after = countCourseWords(fresh);
    console.log(`${doc.courseCode}  ${before} -> ${after} / floor ${floor}  ${after >= floor ? 'PASS ✅ (+' + (after - floor) + ')' : 'STILL SHORT (' + (floor - after) + ')'}  storedWordCount=${fresh.wordCount}`);
  }
  await mongoose.disconnect();
  console.log('\nDone.');
}
main().catch(e => { console.error('ERROR:', e.message); process.exit(1); });
