/**
 * Copyright (c) 2026 CounselorReady, a subsidiary of Ga Integrated Therapeutic Perspectives, LLC.
 * All rights reserved. Proprietary and confidential.
 * Unauthorized copying or distribution is strictly prohibited.
 */
// scripts/updateCrisisCourse.js
// Run: node src/scripts/updateCrisisCourse.js

import mongoose from 'mongoose';
import dotenv from 'dotenv';
dotenv.config();

const connectDB = async () => {
  try {
    await mongoose.connect(process.env.MONGODB_URI);
    console.log('MongoDB Connected');
  } catch (error) {
    console.error('MongoDB error:', error.message);
    process.exit(1);
  }
};

const crisisCourse = {
  title: "Crisis Intervention: Assessment and Response",
  slug: "crisis-intervention",
  description: "This comprehensive 3-hour course prepares mental health professionals to effectively assess and respond to clients in crisis. Through evidence-based frameworks and practical case studies, participants will master suicide risk assessment using the Columbia Protocol and other validated tools, collaborative safety planning using the Stanley-Brown model, verbal de-escalation techniques for agitated clients, and essential post-crisis follow-up protocols. This course addresses the critical skills every clinician needs when working with clients in acute distress, including how to differentiate crisis types, assess lethality, make hospitalization decisions, and maintain clinician wellbeing when doing this demanding work.",
  thumbnail: "https://images.unsplash.com/photo-1516574187841-cb9cc2ca948b?w=800",
  ceHours: 3,
  ceProvider: "NBCC ACEP #7760 - CounselorReady",
  acepNumber: "7760",
  targetAudience: ["Licensed Professional Counselors", "Clinical Social Workers", "Psychologists", "Crisis Workers", "School Counselors", "Substance Abuse Counselors"],
  categories: ["Crisis Intervention", "Clinical Practice", "Risk Assessment", "Suicide Prevention"],
  tags: ["crisis", "suicide", "safety planning", "de-escalation", "risk assessment", "Columbia Protocol", "988", "hospitalization"],
  author: "CounselorReady",
  status: "published",
  publishedAt: new Date(),
  
  // ACEP REQUIRED: Learning Objectives
  learningObjectives: [
    "Define crisis and differentiate between crisis types (developmental, situational, existential, societal)",
    "Apply crisis theory principles to understand client responses and intervention timing",
    "Conduct comprehensive suicide risk assessments using evidence-based tools and frameworks",
    "Develop collaborative safety plans that address client-specific risk and protective factors",
    "Demonstrate effective de-escalation techniques for agitated or distressed clients",
    "Identify appropriate levels of care and make informed referral decisions",
    "Implement post-crisis follow-up protocols to support client stabilization",
    "Recognize clinician stress responses and apply self-care strategies"
  ],
  
  // ACEP REQUIRED: Instructor Credentials
  instructorCredentials: {
    name: "Kejuiana Johnson, MA, LPC, CPCS, BC-TMH",
    credentials: "Licensed Professional Counselor, Certified Professional Counselor Supervisor, Board Certified in Telemental Health",
    organization: "GA Integrated Therapeutic Perspectives LLC",
    bio: "Kejuiana Johnson is a licensed mental health professional with extensive experience in crisis intervention and clinical supervision. She is the founder of CounselorReady, an NBCC-approved continuing education provider dedicated to delivering high-quality professional development for mental health clinicians."
  },
  
  // ACEP REQUIRED: Bibliography/References
  bibliography: [
    {
      citation: "James, R. K., & Gilliland, B. E. (2017). Crisis intervention strategies (8th ed.). Cengage Learning.",
      type: "book"
    },
    {
      citation: "Joiner, T. E. (2005). Why people die by suicide. Harvard University Press.",
      type: "book"
    },
    {
      citation: "Stanley, B., & Brown, G. K. (2012). Safety planning intervention: A brief intervention to mitigate suicide risk. Cognitive and Behavioral Practice, 19(2), 256-264.",
      type: "journal"
    },
    {
      citation: "Rudd, M. D., et al. (2006). Warning signs for suicide: Theory, research, and clinical applications. Suicide and Life-Threatening Behavior, 36(3), 255-262.",
      type: "journal"
    },
    {
      citation: "Roberts, A. R. (Ed.). (2005). Crisis intervention handbook: Assessment, treatment, and research (3rd ed.). Oxford University Press.",
      type: "book"
    },
    {
      citation: "Suicide Prevention Resource Center. (2020). Recommended standard care for people with suicide risk. Education Development Center.",
      type: "report"
    }
  ],
  
  // ACEP REQUIRED: Completion Requirements
  completionRequirements: {
    passingScore: 80,
    mustCompleteAllModules: true,
    mustPassAssessment: true,
    mustCompleteEvaluation: true,
    description: "To receive CE credit, participants must: (1) Complete all course modules, (2) Pass the final assessment with a score of 80% or higher, and (3) Complete the course evaluation."
  },
  
  // Accessibility & Platform Settings
  settings: {
    linearProgression: false,
    certificateEnabled: true,
    passingScore: 80,
    allowRetakes: true,
    retakePolicy: 'unlimited',
    maxRetakes: 3,
    scorePolicy: 'highest',
    requireEvaluation: true,
    requireAttestation: true,
    narrationEnabled: true,
    narrationVoice: 'nova',
    narrationSpeed: 1.0,
    autoPlayNarration: false,
    translationEnabled: true,
    supportedLanguages: ['en', 'es', 'fr', 'de', 'pt', 'zh', 'ko', 'vi'],
    defaultLanguage: 'en',
    highContrastSupported: true,
    fontSizeAdjustable: true,
    screenReaderOptimized: true,
    altTextRequired: true
  },
  
  resources: [
    { title: "Suicide Risk Assessment Guide", type: "checklist", url: "https://res.cloudinary.com/dzfscjhdx/raw/upload/resources/crisis/suicide-risk-assessment.pdf", size: "267 KB" },
    { title: "Safety Plan Template", type: "worksheet", url: "https://res.cloudinary.com/dzfscjhdx/raw/upload/resources/crisis/safety-plan-template.pdf", size: "198 KB" },
    { title: "De-escalation Techniques Card", type: "card", url: "https://res.cloudinary.com/dzfscjhdx/raw/upload/resources/crisis/de-escalation-card.pdf", size: "156 KB" },
    { title: "Crisis Resources List", type: "pdf", url: "https://res.cloudinary.com/dzfscjhdx/raw/upload/resources/crisis/crisis-resources.pdf", size: "178 KB" }
  ],
  sections: [
    {
      title: "Understanding Crisis",
      description: "Defining crisis, types, and theoretical foundations",
      order: 1,
      estimatedTime: 35,
      contentBlocks: [
        { type: "sectionDivider", order: 1, sectionNumber: 1, title: "Understanding Crisis", subtitle: "Foundations of Crisis Intervention" },
        { type: "text", order: 2, textContent: "<h3>What is a Crisis?</h3><p>A crisis occurs when a person faces an obstacle to important life goals that cannot be overcome through customary problem-solving methods. It is a <strong>time-limited state</strong> of psychological disequilibrium—a turning point where the outcome can go either toward growth or deterioration.</p><p>Chinese wisdom captures this dual nature: the Chinese word for 'crisis' combines characters representing 'danger' and 'opportunity.' This ancient insight aligns perfectly with modern crisis theory—how we intervene during crisis can determine whether the outcome leads to new strengths and coping abilities, or to increased vulnerability and dysfunction.</p><p><strong>Key Characteristics of Crisis:</strong></p><ul><li><strong>Precipitating event:</strong> An identifiable trigger that disrupts the person's equilibrium</li><li><strong>Perception of threat:</strong> The event is experienced as overwhelming or dangerous to important life goals</li><li><strong>Exhausted coping:</strong> The person's usual problem-solving strategies have failed or are insufficient for this situation</li><li><strong>Evidence of distress:</strong> Emotional, cognitive, behavioral, and physical symptoms of disequilibrium</li><li><strong>Functional impairment:</strong> Difficulty maintaining normal daily activities and responsibilities</li><li><strong>Time-limited:</strong> The acute crisis state cannot be sustained indefinitely (typically 4-6 weeks)</li><li><strong>Openness to change:</strong> People in crisis are more receptive to intervention and help than at other times</li></ul><p><strong>Clinical Implication:</strong> Understanding these characteristics helps clinicians recognize when someone is truly in crisis versus simply experiencing a difficult situation, and guides the intensity and urgency of our response.</p>" },
        { type: "accordion", order: 3, accordionItems: [
          { title: "Types of Crises", content: "<p><strong>Developmental/Maturational:</strong> Predictable life transitions that can trigger crisis responses. Examples include adolescence, leaving home, marriage, parenthood, midlife transitions, retirement, and aging. While predictable, these transitions can still overwhelm coping resources.</p><p><strong>Situational:</strong> Unexpected events that disrupt equilibrium. Examples include job loss, accidents, unexpected diagnosis, natural disasters, assault, or sudden death of a loved one. The key factor is that these events occur without warning and exceed normal coping capacity.</p><p><strong>Existential:</strong> Inner conflicts about meaning, purpose, identity, and existence. Often triggered by significant life events but focused on fundamental questions: What is my purpose? What happens after death? Does my life matter? These crises may not have obvious external triggers.</p><p><strong>Societal/Environmental:</strong> Crises affecting entire communities. Examples include natural disasters, pandemics (such as COVID-19), community violence, war, and economic collapse. These require understanding both individual and collective trauma responses.</p><p><strong>Psychiatric Crisis:</strong> Acute exacerbation of mental health symptoms, including psychotic episodes, severe dissociation, acute suicidality, panic attacks, or dangerous behavior related to psychiatric conditions. These often require immediate professional intervention and may involve hospitalization.</p>" },
          { title: "Crisis Theory: Caplan & Lindemann's Foundational Model", content: "<p>Modern crisis theory emerged from the work of Erich Lindemann's study of grief following the Cocoanut Grove fire (1944) and Gerald Caplan's work in community mental health. Key principles include:</p><ul><li><strong>Crisis is time-limited:</strong> The acute crisis state typically resolves within 4-6 weeks, for better or worse. The human organism cannot sustain crisis-level arousal indefinitely.</li><li><strong>Openness to change:</strong> During crisis, people are more open to intervention and change than at other times. This creates a window of opportunity.</li><li><strong>Small interventions, big impact:</strong> A relatively brief intervention during crisis can have more impact than extensive therapy at other times.</li><li><strong>Resolution leads to growth OR deterioration:</strong> How a crisis is resolved affects future functioning. Adaptive resolution builds coping skills; maladaptive resolution increases vulnerability.</li><li><strong>Previous responses predict current response:</strong> How someone handled past crises indicates how they may handle current ones. This is valuable assessment information.</li></ul><p><strong>Clinical Implication:</strong> The crisis period is a critical window. Timely, effective intervention can set the trajectory for recovery, while delayed or inadequate response may lead to chronic difficulties.</p>" },
          { title: "The Crisis State: Recognizing Signs", content: "<p>Crisis manifests across multiple domains. Learn to recognize these signs:</p><p><strong>Cognitive Signs:</strong></p><ul><li>Confusion and disorientation</li><li>Poor concentration and attention</li><li>Difficulty making decisions</li><li>Distorted perception of events</li><li>Impaired problem-solving ability</li><li>Intrusive thoughts or images</li><li>Tunnel vision and narrowed perspective</li></ul><p><strong>Emotional Signs:</strong></p><ul><li>Anxiety, panic, fear</li><li>Anger, irritability, rage</li><li>Sadness, grief, despair</li><li>Hopelessness, helplessness</li><li>Guilt, shame</li><li>Emotional numbness or detachment</li><li>Rapid mood swings</li></ul><p><strong>Behavioral Signs:</strong></p><ul><li>Agitation, restlessness, pacing</li><li>Withdrawal, isolation</li><li>Impulsivity, reckless behavior</li><li>Changes in eating or sleeping</li><li>Increased substance use</li><li>Difficulty with daily tasks</li><li>Crying spells or emotional outbursts</li></ul><p><strong>Physical Signs:</strong></p><ul><li>Sleep disturbances</li><li>Appetite changes</li><li>Fatigue, exhaustion</li><li>Headaches, muscle tension</li><li>Gastrointestinal distress</li><li>Increased startle response</li><li>Racing heart, sweating, trembling</li></ul>" },
          { title: "Crisis vs. Emergency: An Important Distinction", content: "<p>Understanding this distinction guides intervention decisions:</p><p><strong>Crisis (Psychological Disequilibrium):</strong></p><ul><li>Person is overwhelmed but not necessarily in immediate danger</li><li>Coping resources are temporarily exceeded</li><li>May resolve with support and time</li><li>Requires clinical intervention but not necessarily emergency response</li></ul><p><strong>Emergency (Immediate Threat to Life):</strong></p><ul><li>Immediate danger to self or others</li><li>Requires urgent action—often same day or hour</li><li>May require hospitalization, police involvement, or medical intervention</li><li>Cannot wait for scheduled appointment</li></ul><p><strong>Key Point:</strong> All emergencies are crises, but not all crises are emergencies. A person can be in significant crisis without being an emergency (e.g., struggling with divorce, grief, job loss). Accurate assessment determines the appropriate level of response.</p><p><strong>Questions to Assess Emergency Status:</strong></p><ul><li>Is there imminent danger to life (suicide, homicide)?</li><li>Are there means available and accessible?</li><li>Is there a timeline for dangerous action?</li><li>Can the person contract for safety and mean it?</li><li>Are protective factors sufficient to maintain safety?</li></ul>" },
          { title: "Roberts' Seven-Stage Crisis Intervention Model", content: "<p>Albert Roberts developed a widely-used framework for crisis intervention:</p><p><strong>Stage 1: Plan and Conduct Crisis Assessment</strong></p><ul><li>Assess lethality and safety needs first</li><li>Evaluate current functioning and coping</li><li>Identify precipitating events</li></ul><p><strong>Stage 2: Establish Rapport and Therapeutic Relationship</strong></p><ul><li>Create safety through your presence</li><li>Use active listening and empathy</li><li>Convey hope without minimizing</li></ul><p><strong>Stage 3: Identify Major Problems</strong></p><ul><li>Prioritize what needs immediate attention</li><li>Focus on the precipitating event</li><li>Identify what's most distressing right now</li></ul><p><strong>Stage 4: Deal with Feelings and Emotions</strong></p><ul><li>Allow expression and validation</li><li>Normalize the crisis response</li><li>Help name and contain emotions</li></ul><p><strong>Stage 5: Generate and Explore Alternatives</strong></p><ul><li>Brainstorm options collaboratively</li><li>Identify what has worked before</li><li>Explore resources and supports</li></ul><p><strong>Stage 6: Develop Action Plan</strong></p><ul><li>Create specific, concrete next steps</li><li>Identify who will do what, when</li><li>Plan for obstacles</li></ul><p><strong>Stage 7: Follow Up</strong></p><ul><li>Schedule follow-up contact</li><li>Verify plan implementation</li><li>Adjust as needed</li></ul>" }
        ]},
        { type: "imageText", order: 4, image: "https://images.unsplash.com/photo-1516574187841-cb9cc2ca948b?w=600", imageAlt: "Support during crisis", imagePosition: "right", title: "Crisis as Opportunity for Transformation", content: "<p>Crisis intervention done well can be a profound turning point — an opportunity for growth, development of new coping skills, strengthened relationships, and positive life change. Many people report that navigating a crisis successfully left them stronger than before.</p><p>Our role as clinicians is to help people navigate the danger while opening doors to opportunity. We serve as a bridge, providing stability and support during the acute phase while helping clients discover inner resources they didn't know they had.</p><p>Remember: The Chinese symbol for crisis combines danger and opportunity. Both are always present.</p>", highlight: true },
        { type: "multipleChoice", order: 5, question: "A crisis is typically time-limited, lasting approximately:", options: [{ text: "24-48 hours", isCorrect: false }, { text: "4-6 weeks", isCorrect: true }, { text: "6-12 months", isCorrect: false }, { text: "Indefinitely", isCorrect: false }], explanation: "Crises typically resolve within 4-6 weeks — for better or worse." },
        { type: "reflection", order: 6, title: "Clinical Reflection: Crisis as Opportunity", prompt: "Think about a client (or yourself) who experienced a crisis. How did it resolve — did it lead to growth or deterioration? What factors influenced the outcome? How might understanding crisis theory change how you frame crisis situations with clients in your practice?", placeholder: "Reflect on your experience with crisis and how it shapes your clinical perspective...", minLength: 100 }
      ],
      hasQuiz: true, quizPassThreshold: 0.8,
      quizQuestions: [
        { question: "Which crisis type involves predictable life transitions?", type: "multipleChoice", options: [{ text: "Situational", isCorrect: false }, { text: "Developmental/Maturational", isCorrect: true }, { text: "Existential", isCorrect: false }, { text: "Societal", isCorrect: false }], explanation: "Developmental crises involve predictable transitions like adolescence, marriage, retirement, and aging." },
        { question: "According to crisis theory, the acute crisis state typically resolves within:", type: "multipleChoice", options: [{ text: "24-48 hours", isCorrect: false }, { text: "4-6 weeks", isCorrect: true }, { text: "6-12 months", isCorrect: false }, { text: "It does not resolve without therapy", isCorrect: false }], explanation: "Crisis states are time-limited, typically resolving within 4-6 weeks—for better or worse." },
        { question: "Which statement about crisis intervention is TRUE?", type: "multipleChoice", options: [{ text: "Crisis intervention requires months of therapy", isCorrect: false }, { text: "Small interventions during crisis can have significant impact", isCorrect: true }, { text: "People in crisis are resistant to change", isCorrect: false }, { text: "Crisis always leads to deterioration", isCorrect: false }], explanation: "During crisis, people are more open to change, and relatively brief interventions can have disproportionately large positive effects." }
      ]
    },
    {
      title: "Suicide Risk Assessment",
      description: "Comprehensive approach to assessing suicide risk",
      order: 2,
      estimatedTime: 45,
      contentBlocks: [
        { type: "sectionDivider", order: 1, sectionNumber: 2, title: "Suicide Risk Assessment", subtitle: "Identifying and Evaluating Risk" },
        { type: "text", order: 2, textContent: "<h3>The Critical Importance of Suicide Risk Assessment</h3><p>Suicide is a leading cause of death across all age groups. In the United States alone, over 48,000 people die by suicide annually—one death every 11 minutes. For every death, there are approximately 25 attempts and many more who experience suicidal thoughts.</p><p><strong>Every mental health clinician will encounter suicidal clients.</strong> This is not a question of 'if' but 'when.' Competent risk assessment is not optional—it's an essential clinical skill that must be practiced regularly.</p><p><strong>Key Principle:</strong> Always ask directly about suicide. Decades of research consistently shows that asking about suicide does NOT increase risk, does NOT 'plant ideas,' and does NOT cause someone to act on thoughts they wouldn't otherwise have had. In fact, asking directly often provides relief and opens the door to help.</p><p>What DOES increase risk is failing to ask, missing warning signs, and leaving people alone with their pain.</p>" },
        { type: "accordion", order: 3, accordionItems: [
          { title: "Risk Factors: What Increases Suicide Risk", content: "<p>Risk factors are characteristics that increase the likelihood of suicide. They don't predict suicide, but they help identify who needs closer assessment. Consider factors across multiple domains:</p><p><strong>Historical Risk Factors:</strong></p><ul><li><strong>Previous suicide attempts:</strong> This is the single strongest predictor of future suicide. The risk is highest in the first year after an attempt, especially the first 3 months.</li><li><strong>Family history of suicide:</strong> Suicide in first-degree relatives increases risk, likely through both genetic and learned factors.</li><li><strong>History of trauma or abuse:</strong> Childhood trauma, sexual abuse, physical abuse, and neglect all increase lifetime suicide risk.</li><li><strong>Previous psychiatric hospitalization:</strong> The period immediately after discharge is particularly high-risk.</li></ul><p><strong>Clinical Risk Factors:</strong></p><ul><li><strong>Depression:</strong> Especially with hopelessness, which is more predictive than depression severity alone.</li><li><strong>Bipolar disorder:</strong> Particularly during mixed episodes or depressive phases.</li><li><strong>Substance use disorders:</strong> Alcohol and drugs impair judgment and lower inhibitions.</li><li><strong>Psychotic disorders:</strong> Especially with command hallucinations telling person to harm themselves.</li><li><strong>Anxiety disorders:</strong> Particularly panic disorder and PTSD.</li><li><strong>Personality disorders:</strong> Especially borderline personality disorder.</li><li><strong>Chronic pain or medical illness:</strong> Terminal diagnoses, chronic pain, and loss of function increase risk.</li></ul><p><strong>Situational Risk Factors:</strong></p><ul><li><strong>Recent losses:</strong> Death of loved one, relationship ending, job loss, financial crisis.</li><li><strong>Access to lethal means:</strong> Firearms in the home are a major risk factor—most firearm suicide attempts are fatal.</li><li><strong>Social isolation:</strong> Living alone, lack of social support, recent move.</li><li><strong>Recent humiliation or shame:</strong> Public embarrassment, legal problems, scandal.</li><li><strong>Exposure to suicide:</strong> Friend or family member's suicide, media coverage, suicide clusters.</li><li><strong>Barriers to mental health care:</strong> Lack of access, stigma, previous negative experiences.</li></ul>" },
          { title: "Protective Factors: What Reduces Risk", content: "<p>Protective factors buffer against suicide risk. However, they do NOT cancel out risk factors—a person can have strong protective factors AND still be at high risk. Always assess both.</p><p><strong>Internal Protective Factors:</strong></p><ul><li><strong>Reasons for living:</strong> Children, pets, future goals, unfinished projects, people who depend on them.</li><li><strong>Future orientation and hope:</strong> Ability to imagine a better future, plans and goals.</li><li><strong>Problem-solving skills:</strong> History of overcoming difficulties, cognitive flexibility.</li><li><strong>Fear of death or dying:</strong> Some people are deterred by fear of the dying process.</li><li><strong>Moral or religious objections:</strong> Beliefs that suicide is wrong or sinful.</li></ul><p><strong>External Protective Factors:</strong></p><ul><li><strong>Social support:</strong> Strong connections to family, friends, community.</li><li><strong>Therapeutic relationship:</strong> Engaged in treatment with a trusted provider.</li><li><strong>Restricted access to means:</strong> No firearms, limited medication access.</li><li><strong>Responsibility for others:</strong> Caring for children, elderly parents, pets.</li><li><strong>Pregnancy:</strong> Suicide rates are lower during pregnancy (but postpartum is higher risk).</li></ul><p><strong>Important Caution:</strong></p><ul><li>Do not assume protective factors make someone 'safe.'</li><li>People can act against their stated reasons for living.</li><li>Assess both risk AND protective factors, but let risk factors drive the level of intervention.</li><li>Protective factors can help with safety planning but shouldn't provide false reassurance.</li></ul>" },
          { title: "Warning Signs: Recognizing Acute Risk", content: "<p>Warning signs are observable behaviors that indicate someone may be moving toward suicide. Unlike risk factors (which are more static), warning signs suggest imminent or near-term danger.</p><p><strong>Immediate Warning Signs (Require Urgent Action):</strong></p><ul><li>Threatening to hurt or kill oneself—take ALL threats seriously</li><li>Looking for ways to kill oneself—searching online, asking about methods</li><li>Talking or writing about death, dying, or suicide</li><li>Giving away prized possessions</li><li>Saying goodbye to loved ones as if they won't see them again</li><li>Putting affairs in order (will, insurance, passwords)</li><li>Sudden calmness after period of depression (may indicate decision has been made)</li></ul><p><strong>Behavioral Warning Signs:</strong></p><ul><li>Increased alcohol or drug use</li><li>Withdrawing from family, friends, activities</li><li>Sleeping too much or too little</li><li>Dramatic mood changes</li><li>Acting recklessly, engaging in risky activities</li><li>Visiting or calling people to say goodbye</li><li>Aggression, rage, seeking revenge</li></ul><p><strong>Verbal Warning Signs (Direct and Indirect):</strong></p><ul><li><strong>Direct:</strong> 'I want to kill myself,' 'I wish I were dead,' 'I'm going to end it'</li><li><strong>Indirect:</strong> 'Everyone would be better off without me,' 'I can't take it anymore,' 'What's the point?' 'Soon it won't matter,' 'I won't be around much longer'</li></ul><p><strong>Remember:</strong> Many people who die by suicide showed warning signs. The key is recognizing them and responding appropriately.</p>" },
          { title: "The Columbia Protocol (C-SSRS): A Standardized Screening Tool", content: "<p>The Columbia Suicide Severity Rating Scale (C-SSRS) is an evidence-based tool used worldwide to identify suicide risk. It uses a series of questions that progressively assess severity of ideation.</p><p><strong>Screening Questions (adapted from C-SSRS):</strong></p><ol><li><strong>Wish to be Dead:</strong> 'Have you wished you were dead or wished you could go to sleep and not wake up?'</li><li><strong>Suicidal Thoughts:</strong> 'Have you actually had any thoughts of killing yourself?'</li></ol><p><em>If YES to Question 2, continue:</em></p><ol start='3'><li><strong>Suicidal Thoughts with Method:</strong> 'Have you been thinking about how you might do this?'</li><li><strong>Suicidal Intent:</strong> 'Have you had these thoughts and had some intention of acting on them?'</li><li><strong>Suicide Intent with Specific Plan:</strong> 'Have you started to work out or worked out the details of how to kill yourself? Do you intend to carry out this plan?'</li></ol><p><strong>Assessing Suicidal Behavior:</strong></p><ol start='6'><li>'Have you done anything, started to do anything, or prepared to do anything to end your life?'</li></ol><p><strong>Interpreting Responses:</strong></p><ul><li>YES to Q1 only: Passive ideation—monitor, assess further</li><li>YES to Q2: Active ideation—requires clinical assessment</li><li>YES to Q3: Ideation with method—elevated concern</li><li>YES to Q4: Intent present—high concern, safety planning needed</li><li>YES to Q5: Intent with plan—high risk, consider hospitalization</li><li>YES to Q6: Recent behavior—imminent risk, urgent intervention</li></ul><p>The C-SSRS is available free at cssrs.columbia.edu and has versions for different settings and populations.</p>" },
          { title: "The 4 P's: A Clinical Assessment Framework", content: "<p>When assessing suicidal ideation, explore the 4 P's to understand the nature and severity of risk:</p><p><strong>1. PLAN</strong></p><ul><li>Do they have a specific plan for how they would kill themselves?</li><li>How detailed and concrete is the plan?</li><li>Is the plan lethal and feasible?</li><li>Have they identified a specific method, location, time?</li><li>More specific = higher risk</li></ul><p><strong>2. PREPARATION</strong></p><ul><li>Have they taken any steps toward carrying out the plan?</li><li>Have they acquired means (pills, weapon, rope)?</li><li>Have they researched methods online?</li><li>Have they written a suicide note?</li><li>Have they given away possessions?</li><li>Any preparation = significantly elevated risk</li></ul><p><strong>3. PRIOR ATTEMPTS</strong></p><ul><li>Have they attempted suicide before?</li><li>How many attempts? How recent?</li><li>What methods were used?</li><li>How lethal were the attempts?</li><li>What stopped them or led to rescue?</li><li>Previous attempts = strongest predictor of future suicide</li></ul><p><strong>4. PURPOSE</strong></p><ul><li>What do they hope to achieve through suicide?</li><li>Escape from pain? Revenge? Relief for others?</li><li>Do they see any other way to achieve this goal?</li><li>Understanding purpose helps identify intervention points</li></ul><p><strong>Additional Critical Questions:</strong></p><ul><li><strong>Timeline:</strong> When do they intend to act? Today? This week? Someday?</li><li><strong>Means access:</strong> Do they have access to the method in their plan?</li><li><strong>Ambivalence:</strong> Is any part of them that wants to live?</li><li><strong>Deterrents:</strong> What has stopped them so far?</li><li><strong>Reasons for living:</strong> What keeps them going?</li></ul>" },
          { title: "Determining Risk Level: Low, Moderate, High, Imminent", content: "<p>Based on your assessment, determine the overall risk level to guide intervention intensity:</p><p><strong>LOW RISK:</strong></p><ul><li>Ideation without specific plan</li><li>No intent to act</li><li>Strong protective factors</li><li>Engaged in treatment</li><li>No history of attempts</li><li>Limited access to means</li></ul><p><em>Intervention:</em> Continue outpatient treatment, safety planning, increase contact if needed, remove or restrict means.</p><p><strong>MODERATE RISK:</strong></p><ul><li>Ideation with some plan but no immediate intent</li><li>Ambivalence present (reasons for living)</li><li>Some protective factors</li><li>May have history of attempts</li><li>Some access to means</li></ul><p><em>Intervention:</em> Safety planning, more frequent contact, means restriction, consider intensive outpatient, consult with colleagues, involve family/supports.</p><p><strong>HIGH RISK:</strong></p><ul><li>Ideation with plan AND intent</li><li>Access to lethal means</li><li>Recent attempt or rehearsal behavior</li><li>Few protective factors</li><li>Hopelessness prominent</li><li>Limited social support</li></ul><p><em>Intervention:</em> Safety planning, immediate means restriction, consider voluntary hospitalization, crisis services, continuous observation if needed, involve family urgently.</p><p><strong>IMMINENT RISK:</strong></p><ul><li>Plan, intent, and timeline (planning to act soon)</li><li>Means available and accessible</li><li>Unable or unwilling to commit to safety</li><li>No protective factors engaged</li><li>Command hallucinations to harm self</li><li>Intoxication with suicidal intent</li></ul><p><em>Intervention:</em> Do not leave alone, emergency psychiatric evaluation, involuntary hospitalization if necessary, call 911 if unable to transport safely.</p>" }
        ]},
        { type: "imageText", order: 4, image: "https://images.unsplash.com/photo-1573497019940-1c28c88b4f3e?w=600", imageAlt: "Therapeutic conversation", imagePosition: "left", title: "Levels of Risk", content: "<p><strong>Low Risk:</strong> Ideation without plan, strong protective factors, engaged in treatment</p><p><strong>Moderate Risk:</strong> Ideation with plan but no intent or timeline, some protective factors</p><p><strong>High Risk:</strong> Ideation with plan AND intent, access to means, few protective factors, recent attempt or rehearsal</p><p><strong>Imminent Risk:</strong> Plan, intent, timeline, means available, no protective factors — requires immediate action</p>", highlight: true },
        { type: "multipleChoice", order: 5, question: "What is the single strongest predictor of future suicide?", options: [{ text: "Depression diagnosis", isCorrect: false }, { text: "Family history of mental illness", isCorrect: false }, { text: "Previous suicide attempt", isCorrect: true }, { text: "Substance abuse", isCorrect: false }], explanation: "Previous suicide attempt is the strongest predictor of future suicide." },
        { type: "reflection", order: 6, title: "Clinical Reflection: Asking About Suicide", prompt: "How comfortable are you asking clients directly about suicide? What barriers (your own discomfort, fear of 'planting ideas') have you experienced? How might you practice or improve your suicide risk assessment skills?", placeholder: "Reflect on your comfort level and approach to suicide assessment...", minLength: 100 }
      ],
      hasQuiz: true, quizPassThreshold: 0.8,
      quizQuestions: [
        { question: "Asking directly about suicide:", type: "multipleChoice", options: [{ text: "Increases the risk of suicide", isCorrect: false }, { text: "Plants ideas in the client's head", isCorrect: false }, { text: "Does NOT increase risk and is essential", isCorrect: true }, { text: "Should be avoided with depressed clients", isCorrect: false }], explanation: "Research consistently shows asking about suicide does NOT increase risk." },
        { question: "The 4 P's of suicide assessment include all EXCEPT:", type: "multipleChoice", options: [{ text: "Plan", isCorrect: false }, { text: "Preparation", isCorrect: false }, { text: "Prior attempts", isCorrect: false }, { text: "Personality", isCorrect: true }], explanation: "The 4 P's are Plan, Preparation, Prior attempts, and Purpose." }
      ]
    },
    {
      title: "Safety Planning",
      description: "Creating effective safety plans with clients",
      order: 3,
      estimatedTime: 35,
      contentBlocks: [
        { type: "sectionDivider", order: 1, sectionNumber: 3, title: "Safety Planning", subtitle: "Collaborative Crisis Prevention" },
        { type: "text", order: 2, textContent: "<h3>What is a Safety Plan?</h3><p>A safety plan is a prioritized, written list of coping strategies and resources that clients can use during a suicidal crisis. Developed by Barbara Stanley and Gregory Brown, the Safety Planning Intervention (SPI) has strong research support showing it reduces suicidal behavior and suicide attempts.</p><p>Safety plans differ fundamentally from outdated 'no-suicide contracts' (also called 'contracts for safety'). Research shows that no-suicide contracts are <strong>not effective</strong> at preventing suicide—they provide false reassurance and may actually be harmful by substituting for proper assessment and intervention.</p><p><strong>Key Characteristics of Effective Safety Plans:</strong></p><ul><li><strong>Collaborative:</strong> Developed WITH the client, not FOR them. Uses their words, not clinical jargon.</li><li><strong>Specific:</strong> Contains concrete names, phone numbers, activities—not vague categories.</li><li><strong>Prioritized:</strong> Steps are arranged in order, starting with internal strategies before moving to external resources.</li><li><strong>Accessible:</strong> Client keeps a copy where they'll see and use it (phone, wallet, refrigerator).</li><li><strong>Practiced:</strong> Review and rehearse before crisis—don't wait until crisis to learn it.</li><li><strong>Living document:</strong> Updated as circumstances change, resources shift, or strategies prove effective or ineffective.</li></ul>" },
        { type: "accordion", order: 3, accordionItems: [
          { title: "Step 1: Warning Signs - Recognizing When Crisis is Building", content: "<p>Help the client identify their personal warning signs that indicate a crisis may be developing. These are the internal signals that tell them it's time to use the safety plan.</p><p><strong>Explore Each Domain:</strong></p><ul><li><strong>Thoughts:</strong> 'What thoughts tell you a crisis might be building?' Examples: 'Everyone would be better off without me,' 'I can't do this anymore,' 'What's the point?'</li><li><strong>Feelings:</strong> 'What emotions do you notice when you're heading toward crisis?' Examples: Hopelessness, overwhelming sadness, numbness, rage, panic, feeling trapped.</li><li><strong>Behaviors:</strong> 'What do you start doing differently?' Examples: Isolating, not returning calls, drinking more, stopping medications, neglecting hygiene.</li><li><strong>Physical sensations:</strong> 'What does your body feel like?' Examples: Heaviness, chest tightness, nausea, inability to sleep, loss of appetite.</li></ul><p><strong>Be Specific:</strong> 'Feeling bad' is too vague to be useful. Work with the client to identify concrete, recognizable signs like: 'When I stay in bed past noon, stop showering, and have thoughts that I'm a burden, those are my warning signs.'</p><p><strong>Why This Matters:</strong> Early recognition allows intervention before the crisis escalates. The goal is to use the safety plan BEFORE reaching the point of imminent danger.</p>" },
          { title: "Step 2: Internal Coping Strategies - What I Can Do Alone", content: "<p>These are activities the client can do ON THEIR OWN, without contacting anyone, to reduce distress and ride out urges. The goal is to provide immediate, accessible options that can be used at any time.</p><p><strong>Categories of Internal Coping:</strong></p><p><strong>Distraction Activities:</strong></p><ul><li>Watch a favorite show or movie (list specific titles)</li><li>Play video games (list specific games)</li><li>Do a puzzle, crossword, or sudoku</li><li>Read a book or magazine</li><li>Clean or organize something</li><li>Work on a hobby or craft</li></ul><p><strong>Physical Activities:</strong></p><ul><li>Take a walk (even a short one)</li><li>Exercise, stretch, or do yoga</li><li>Take a shower (alternate hot and cold)</li><li>Do jumping jacks or push-ups</li></ul><p><strong>Sensory Grounding:</strong></p><ul><li>Hold ice cubes</li><li>Smell something strong (coffee, peppermint, citrus)</li><li>Eat something with intense flavor (hot sauce, sour candy)</li><li>Listen to loud music</li><li>5-4-3-2-1 technique (5 things you see, 4 hear, 3 touch, 2 smell, 1 taste)</li></ul><p><strong>Relaxation:</strong></p><ul><li>Deep breathing exercises</li><li>Progressive muscle relaxation</li><li>Guided meditation (list specific apps or recordings)</li><li>Take a bath</li></ul><p><strong>Key Principles:</strong></p><ul><li>List 3-5 specific activities, not general categories</li><li>Include things that have worked before OR that client is willing to try</li><li>Make sure activities are accessible (don't require leaving house, spending money, etc.)</li><li>Include options for different situations (middle of night, at work, etc.)</li></ul>" },
          { title: "Step 3: Social Contacts for Distraction", content: "<p>These are people and places that provide healthy distraction—NOT necessarily people to discuss the crisis with. The goal is connection and normalization, not crisis support.</p><p><strong>People to Contact (for distraction, not crisis discussion):</strong></p><ul><li>List specific names and phone numbers</li><li>Include people who are generally positive and engaging</li><li>Choose people the client can reach without disclosing they're struggling</li><li>Example: 'Call my brother and ask about his kids' or 'Text my friend about our fantasy football league'</li></ul><p><strong>Social Settings to Visit:</strong></p><ul><li>Coffee shop (list specific one)</li><li>Library</li><li>Gym or fitness center</li><li>Religious community events</li><li>Support group meetings (AA, etc.)</li><li>Walking in a populated area</li></ul><p><strong>Online Communities:</strong></p><ul><li>Gaming communities</li><li>Social media groups (positive ones)</li><li>Online forums related to hobbies</li></ul><p><strong>Why Distraction Helps:</strong> Sometimes people in crisis just need to get through the next few hours. Human contact—even without discussing the crisis—can break isolation and help time pass until urges decrease. The suicidal crisis state is temporary; distraction helps survive until it passes.</p>" },
          { title: "Step 4: People I Can Ask for Help", content: "<p>These are people the client can tell they're struggling and ask for support. This step requires more vulnerability than Step 3.</p><p><strong>List Specific People:</strong></p><ul><li>Full names with phone numbers</li><li>Relationship to client</li><li>Best times to reach them</li><li>Usually 2-4 people</li></ul><p><strong>Types of Support People:</strong></p><ul><li>Trusted friends or family members</li><li>Sponsor (if in recovery)</li><li>Faith leader or spiritual advisor</li><li>Mentor or teacher</li><li>Therapist (with contact info and availability)</li></ul><p><strong>Prepare for the Conversation:</strong></p><p>Discuss in advance:</p><ul><li>What might they say? ('I'm really struggling tonight and could use some support')</li><li>What kind of help are they asking for? (company, talking, distraction, help getting to emergency room)</li><li>What if the person doesn't answer?</li><li>What if the person responds unhelpfully?</li></ul><p><strong>Role Play:</strong> Practice making the call in session. This reduces barriers when it's needed for real.</p><p><strong>Inform Supports:</strong> With client permission, consider reaching out to key support people to let them know they may be called upon and how to respond helpfully.</p>" },
          { title: "Step 5: Professional and Crisis Resources", content: "<p>These are professional resources for when personal supports aren't available or the situation requires professional intervention.</p><p><strong>Crisis Hotlines:</strong></p><ul><li><strong>988 Suicide & Crisis Lifeline:</strong> Call or text 988 (24/7, free, confidential)</li><li><strong>Crisis Text Line:</strong> Text HOME to 741741</li><li><strong>Veterans Crisis Line:</strong> 988, Press 1</li><li><strong>Trans Lifeline:</strong> 877-565-8860</li><li><strong>Trevor Project (LGBTQ+ youth):</strong> 1-866-488-7386</li></ul><p><strong>Local Resources:</strong></p><ul><li>Mobile crisis team (include local number)</li><li>Crisis stabilization unit</li><li>Nearest emergency department (with address)</li><li>Community mental health center crisis services</li></ul><p><strong>Therapist Contact:</strong></p><ul><li>Therapist's phone number</li><li>After-hours availability or on-call coverage</li><li>What to do if therapist is unavailable</li></ul><p><strong>When to Use Emergency Services:</strong></p><ul><li>Internal strategies and personal supports haven't helped</li><li>Urges are intensifying despite coping efforts</li><li>Safety is at imminent risk</li><li>Unable to commit to safety</li></ul><p><strong>Address Barriers:</strong> Discuss concerns about calling crisis lines or going to emergency room. Address stigma, past negative experiences, fears about hospitalization.</p>" },
          { title: "Step 6: Means Restriction - Making the Environment Safer", content: "<p>Reducing access to lethal means is one of the <strong>most effective suicide prevention strategies</strong> we have. Research consistently shows that putting time and distance between a person and lethal means saves lives.</p><p><strong>Why Means Restriction Works:</strong></p><ul><li>Most suicidal crises are time-limited—if someone survives the acute period, they often don't attempt later</li><li>Many suicide attempts are impulsive—barriers create time for the impulse to pass</li><li>Method substitution is less common than assumed—people don't simply switch to another method</li><li>Restricting access to one method reduces overall suicide rates</li></ul><p><strong>Firearms (Highest Priority):</strong></p><ul><li>Firearms are involved in over half of U.S. suicide deaths</li><li>Firearm suicide attempts are fatal about 85% of the time</li><li>Options: Store with friend or family, gun safe with key held by someone else, gun shop storage, police department storage</li><li>Remove ammunition as well as firearm</li><li>Even temporary removal during crisis period can be life-saving</li></ul><p><strong>Medications:</strong></p><ul><li>Limit quantities available (smaller prescription fills)</li><li>Have trusted person hold and dispense medications</li><li>Lock medications in a secure container</li><li>Dispose of unused or old medications properly</li></ul><p><strong>Other Means:</strong></p><ul><li>Discuss means specific to client's plan</li><li>Address access to heights, vehicles, sharp objects, ligatures as relevant</li></ul><p><strong>Involving Family/Supports:</strong></p><ul><li>With client consent, involve family members in means restriction</li><li>Provide specific instructions on what to do and how to store items safely</li><li>Follow up to confirm implementation</li></ul><p><strong>Addressing Resistance:</strong></p><ul><li>Some clients resist means restriction—explore their concerns</li><li>Frame as temporary measure during crisis period</li><li>Emphasize collaborative decision-making</li><li>Focus on what client IS willing to do</li></ul>" }
        ]},
        { type: "imageText", order: 4, image: "https://images.unsplash.com/photo-1517048676732-d65bc937f952?w=600", imageAlt: "Collaborative planning", imagePosition: "right", title: "Making Safety Plans Work", content: "<ul><li><strong>Collaborative:</strong> Client's words, not clinician's template</li><li><strong>Specific:</strong> Names, numbers, concrete activities</li><li><strong>Accessible:</strong> Keep it where they'll see it (phone, wallet, fridge)</li><li><strong>Practiced:</strong> Review and rehearse before crisis</li><li><strong>Updated:</strong> Revise as circumstances change</li></ul>", highlight: true },
        { type: "resources", order: 5, title: "Safety Planning Tools", description: "Download these resources", resources: [
          { title: "Safety Plan Template", type: "worksheet", url: "https://res.cloudinary.com/dzfscjhdx/raw/upload/resources/crisis/safety-plan-template.pdf", size: "198 KB" },
          { title: "Crisis Resources List", type: "pdf", url: "https://res.cloudinary.com/dzfscjhdx/raw/upload/resources/crisis/crisis-resources.pdf", size: "178 KB" }
        ]},
        { type: "reflection", order: 6, title: "Clinical Reflection: Creating Effective Safety Plans", prompt: "Think about a safety plan you've created with a client (or imagine creating one). Was it truly collaborative? Were the coping strategies specific and personalized? How might you make your safety planning process more effective?", placeholder: "Reflect on your safety planning approach and areas for improvement...", minLength: 100 }
      ],
      hasQuiz: true, quizPassThreshold: 0.8,
      quizQuestions: [
        { question: "Safety plans differ from 'no-suicide contracts' in that:", type: "multipleChoice", options: [{ text: "They are legally binding", isCorrect: false }, { text: "They are evidence-based and collaborative", isCorrect: true }, { text: "They don't require client input", isCorrect: false }, { text: "They are completed by the clinician alone", isCorrect: false }], explanation: "Safety plans are evidence-based and developed collaboratively with the client." },
        { question: "The most effective suicide prevention strategy is:", type: "multipleChoice", options: [{ text: "No-suicide contracts", isCorrect: false }, { text: "Hospitalization for all suicidal clients", isCorrect: false }, { text: "Means restriction", isCorrect: true }, { text: "Medication only", isCorrect: false }], explanation: "Reducing access to lethal means is one of the most effective strategies." }
      ]
    },
    {
      title: "De-escalation Techniques",
      description: "Skills for managing agitated and distressed clients",
      order: 4,
      estimatedTime: 35,
      contentBlocks: [
        { type: "sectionDivider", order: 1, sectionNumber: 4, title: "De-escalation Techniques", subtitle: "Calming Crisis Situations" },
        { type: "text", order: 2, textContent: "<h3>The Goal of De-escalation</h3><p>De-escalation aims to reduce a person's emotional intensity so they can engage their 'thinking brain' (prefrontal cortex) and participate in problem-solving. When someone is highly agitated, their survival brain is in control—logic and reasoning won't work until they feel safer.</p><p><strong>Key Principle:</strong> It's about <strong>connection before correction</strong>. Before you can solve problems, redirect behavior, or set limits, you must first help the person feel heard and reduce their arousal level.</p><p><strong>Remember:</strong> An agitated person's brain is in survival mode. The amygdala is activated, stress hormones are flooding the system, and the prefrontal cortex (rational thought) is offline. Trying to reason with someone in this state is like trying to have a conversation during an earthquake—the survival system doesn't care about logic.</p><p><strong>Your goal is to help them move from:</strong></p><ul><li>Fight/flight/freeze → Calm engagement</li><li>Amygdala dominance → Prefrontal cortex access</li><li>Survival mode → Problem-solving mode</li></ul>" },
        { type: "accordion", order: 3, accordionItems: [
          { title: "Your Presence Matters: Regulate Yourself First", content: "<p><strong>The most important de-escalation tool is your own regulated nervous system.</strong></p><p>Your emotional state is contagious. If you're calm, that calm can spread to the agitated person. If you're anxious, defensive, or angry, those emotions will escalate the situation.</p><p><strong>Before Engaging:</strong></p><ul><li>Take a deep breath (or several)</li><li>Check your body: Drop your shoulders, unclench your jaw, relax your hands</li><li>Notice your own emotional state—name it to tame it</li><li>Remind yourself: 'This is not about me. This person is in pain.'</li></ul><p><strong>During the Interaction:</strong></p><ul><li>Lower your voice and slow your speech (this naturally calms)</li><li>Keep your body relaxed and open</li><li>Breathe slowly and visibly (they may unconsciously mirror you)</li><li>Project calm confidence—not fear, not aggression</li><li>Move slowly and deliberately</li></ul><p><strong>Internal Self-Talk:</strong></p><ul><li>'I can handle this.'</li><li>'Their behavior is a symptom, not a personal attack.'</li><li>'My calm is the most helpful thing I can offer right now.'</li><li>'I don't need to fix this immediately—I need to create safety first.'</li></ul><p><strong>You cannot de-escalate someone if you're escalated yourself.</strong> If you notice yourself becoming activated, take a moment to regulate before continuing. It's okay to say, 'Give me just a moment' while you take a breath.</p>" },
          { title: "Environmental Factors: Creating Physical Safety", content: "<p>The physical environment can escalate or de-escalate a crisis. Attend to these factors:</p><p><strong>Reduce Stimulation:</strong></p><ul><li>Lower noise levels if possible</li><li>Reduce harsh or bright lighting</li><li>Minimize the number of people present (crowds escalate)</li><li>Turn off TVs, alarms, or other distracting sounds</li></ul><p><strong>Ensure Physical Safety:</strong></p><ul><li>Clear path to exit for BOTH of you (neither should be cornered)</li><li>Position yourself between the person and the door if they're not a flight risk; otherwise ensure they have a clear exit</li><li>Remove or secure potential weapons or throwing objects</li><li>Know where emergency help can be summoned if needed</li></ul><p><strong>Your Positioning:</strong></p><ul><li>Maintain safe distance (at least arm's length, more if person is physically agitated)</li><li>Position yourself at an angle (45 degrees), not directly face-to-face (which can feel confrontational)</li><li>Stay at their eye level if safe (don't tower over them)</li><li>Avoid blocking the door or cornering them</li><li>Keep your hands visible and open</li></ul><p><strong>If Outdoors or Public:</strong></p><ul><li>Move to a quieter area if possible</li><li>Create distance from bystanders</li><li>Be aware of traffic, heights, or other environmental hazards</li></ul>" },
          { title: "Verbal De-escalation: What to Say and How", content: "<p><strong>HOW You Say It (Paralanguage):</strong></p><ul><li>Use a calm, low tone—high pitch conveys anxiety</li><li>Speak slowly—rushed speech increases arousal</li><li>Use short, simple sentences—complex language is hard to process when agitated</li><li>Pause between statements—allow time to process</li><li>Match their volume initially, then gradually lower yours</li></ul><p><strong>WHAT to Say (Content):</strong></p><p><strong>DO:</strong></p><ul><li>Use the person's name (personalizes the interaction)</li><li>Validate feelings: 'I can see you're really upset' / 'This situation is incredibly frustrating'</li><li>Acknowledge their experience: 'It sounds like you've been through a lot today'</li><li>Express genuine interest: 'Help me understand what happened' / 'Tell me more'</li><li>Offer choices: 'Would you like to sit or stand?' / 'Would you like some water?'</li><li>Set clear, simple limits when needed: 'I want to help you, and I need you to lower your voice so we can talk'</li><li>Convey hope: 'We're going to figure this out together'</li></ul><p><strong>DON'T:</strong></p><ul><li>Argue, challenge, or try to prove them wrong</li><li>Threaten consequences ('If you don't calm down...')</li><li>Tell them to 'calm down' or 'relax' (dismissive and invalidating)</li><li>Raise your voice or talk fast</li><li>Use jargon, complex explanations, or too many words</li><li>Make promises you can't keep</li><li>Take insults personally or respond defensively</li><li>Touch them without permission (unless necessary for safety)</li></ul>" },
          { title: "The LEAP Approach: Listen, Empathize, Agree, Partner", content: "<p>LEAP is a structured approach for engaging difficult or agitated individuals, developed by Dr. Xavier Amador:</p><p><strong>L - LISTEN:</strong></p><ul><li>Give full, undivided attention</li><li>Let them talk without interrupting</li><li>Use reflective listening ('What I hear you saying is...')</li><li>Ask clarifying questions with genuine curiosity</li><li>Don't rush to fix or advise</li></ul><p><strong>E - EMPATHIZE:</strong></p><ul><li>Reflect the feelings you observe</li><li>Validate their emotional experience (not necessarily their conclusions)</li><li>'I can see how angry this has made you'</li><li>'That sounds incredibly frustrating'</li><li>'It makes sense you'd feel that way given what happened'</li><li>Empathy is not agreement—you can empathize with feelings while disagreeing with behavior</li></ul><p><strong>A - AGREE:</strong></p><ul><li>Find something—anything—you can genuinely agree with</li><li>Even partial agreement builds alliance</li><li>'You're right that you've been waiting a long time'</li><li>'I agree this situation isn't fair'</li><li>'You're absolutely right that you deserve to be heard'</li><li>This reduces the adversarial dynamic</li></ul><p><strong>P - PARTNER:</strong></p><ul><li>Move toward collaborative problem-solving</li><li>'How can we work together to...'</li><li>'What would be helpful right now?'</li><li>'Let's figure out a solution together'</li><li>Give them agency and choice where possible</li><li>The person becomes a partner in resolution, not an adversary</li></ul><p>LEAP validates the person while moving toward resolution. It works because people calm down when they feel heard.</p>" },
          { title: "When De-escalation Isn't Working", content: "<p>Sometimes de-escalation efforts fail. Know when to change approach or get help:</p><p><strong>Signs De-escalation Isn't Working:</strong></p><ul><li>Agitation is increasing despite your efforts</li><li>Person is becoming physically threatening</li><li>They're not responding to verbal engagement</li><li>You're feeling increasingly unsafe</li><li>The situation has continued for extended time without improvement</li></ul><p><strong>When to Call for Help:</strong></p><ul><li>Physical violence seems imminent</li><li>Person has or is seeking a weapon</li><li>You feel unsafe and unable to improve the situation</li><li>Person needs medical attention</li><li>Involuntary hospitalization may be needed</li><li>You're alone and the situation is deteriorating</li></ul><p><strong>There is no shame in calling for help.</strong> Your safety matters too. Being a hero who gets hurt helps no one.</p><p><strong>Options for Help:</strong></p><ul><li>Coworkers or security personnel</li><li>Mobile crisis team</li><li>911/Police (with appropriate cautions about involving law enforcement in mental health crises)</li><li>On-call psychiatrist or supervisor</li></ul><p><strong>After an Unsuccessful De-escalation:</strong></p><ul><li>Debrief what happened</li><li>Consider what might have worked differently</li><li>Process your own feelings about the incident</li><li>Don't blame yourself—not every situation can be de-escalated</li></ul>" },
          { title: "Special Populations and Considerations", content: "<p><strong>Psychotic Symptoms:</strong></p><ul><li>Don't argue with delusions or hallucinations</li><li>Focus on feelings, not content ('That sounds frightening')</li><li>Keep reality orientation brief and non-confrontational</li><li>Understand they may be responding to internal stimuli you can't see</li></ul><p><strong>Substance Intoxication:</strong></p><ul><li>Judgment and impulse control are impaired</li><li>They may not remember this interaction later</li><li>Focus on immediate safety, not processing</li><li>Medical monitoring may be needed</li></ul><p><strong>Trauma History:</strong></p><ul><li>Avoid triggering further trauma response</li><li>Be especially mindful of physical space and touch</li><li>Let them maintain as much control as possible</li><li>Recognize trauma responses may look like aggression</li></ul><p><strong>Cultural Considerations:</strong></p><ul><li>Eye contact norms vary by culture</li><li>Physical distance expectations differ</li><li>Expression of distress varies culturally</li><li>Be humble about your cultural assumptions</li></ul>" }
        ]},
        { type: "imageText", order: 4, image: "https://images.unsplash.com/photo-1573497019940-1c28c88b4f3e?w=600", imageAlt: "Calm professional presence", imagePosition: "left", title: "De-escalation Phrases", content: "<ul><li>'I want to help you.'</li><li>'I can see this is really hard.'</li><li>'You're safe here.'</li><li>'Help me understand what happened.'</li><li>'What would be helpful right now?'</li><li>'Let's figure this out together.'</li></ul><p><strong>Avoid:</strong> 'Calm down' (dismissive), 'You need to...' (controlling), 'That's not true' (argumentative)</p>", highlight: true },
        { type: "multipleChoice", order: 5, question: "The first step in de-escalation is:", options: [{ text: "Tell the person to calm down", isCorrect: false }, { text: "Call security", isCorrect: false }, { text: "Regulate yourself", isCorrect: true }, { text: "Explain the rules", isCorrect: false }], explanation: "You must regulate yourself first — your calm is contagious." },
        { type: "reflection", order: 6, title: "Clinical Reflection: Managing Your Own Activation", prompt: "When you encounter an agitated or distressed client, what happens in YOUR body and mind? What are your personal strategies for regulating yourself so you can be a calming presence? How might you strengthen your ability to stay regulated under pressure?", placeholder: "Reflect on your own stress responses and regulation strategies in crisis situations...", minLength: 100 }
      ],
      hasQuiz: true, quizPassThreshold: 0.8,
      quizQuestions: [
        { question: "Why doesn't logic work with an agitated person?", type: "multipleChoice", options: [{ text: "They're not intelligent enough", isCorrect: false }, { text: "Their brain is in survival mode", isCorrect: true }, { text: "They're being manipulative", isCorrect: false }, { text: "Logic never works in therapy", isCorrect: false }], explanation: "When agitated, the survival brain takes over and the thinking brain goes offline." },
        { question: "LEAP stands for:", type: "multipleChoice", options: [{ text: "Listen, Evaluate, Act, Proceed", isCorrect: false }, { text: "Listen, Empathize, Agree, Partner", isCorrect: true }, { text: "Learn, Educate, Assess, Plan", isCorrect: false }, { text: "Look, Engage, Approach, Protect", isCorrect: false }], explanation: "LEAP: Listen, Empathize, Agree, Partner." }
      ]
    },
    {
      title: "Post-Crisis Follow-Up",
      description: "Care after the crisis and documentation",
      order: 5,
      estimatedTime: 30,
      contentBlocks: [
        { type: "sectionDivider", order: 1, sectionNumber: 5, title: "Post-Crisis Follow-Up", subtitle: "Continuity of Care" },
        { type: "text", order: 2, textContent: "<h3>The Critical Period After Crisis</h3><p>The days and weeks following a crisis are a <strong>high-risk period</strong> that is often underappreciated. Research consistently shows that suicide risk is significantly elevated in the days immediately following crisis resolution and especially after discharge from psychiatric hospitalization.</p><p><strong>Key Statistics:</strong></p><ul><li>The first week after psychiatric discharge has suicide rates 100-200 times higher than the general population</li><li>Approximately 25% of suicide deaths occur within 3 months of psychiatric contact</li><li>The risk of repeat suicide attempt is highest in the first 3-6 months after an attempt</li></ul><p><strong>Why the Post-Crisis Period is Dangerous:</strong></p><ul><li>Crisis supports are withdrawn (hospital, intensive services)</li><li>Client may feel exhausted or embarrassed after the crisis</li><li>Underlying problems haven't been resolved—just the acute crisis</li><li>Others may assume the person is 'better' and reduce support</li><li>If crisis involved an attempt, physical recovery may precede emotional recovery</li></ul><p><strong>Bottom line: Follow-up is not optional—it's essential care.</strong></p>" },
        { type: "accordion", order: 3, accordionItems: [
          { title: "Immediate Follow-Up (24-72 hours)", content: "<p>The first days after crisis are critical. Don't assume 'no news is good news.'</p><p><strong>Actions to Take:</strong></p><ul><li><strong>Contact the client:</strong> Phone call, text, or scheduled session within 24-72 hours</li><li><strong>Check on safety:</strong> Are they still safe? Have circumstances changed?</li><li><strong>Review safety plan:</strong> Remind them where it is and how to use it</li><li><strong>Verify resources:</strong> Ensure they have crisis numbers accessible</li><li><strong>Confirm next appointment:</strong> Don't let them fall through the cracks</li><li><strong>Coordinate care:</strong> If other providers are involved, communicate with them</li></ul><p><strong>What to Document:</strong></p><ul><li>Date and time of follow-up contact</li><li>Client's current status and safety</li><li>Any changes since last contact</li><li>Plan discussed</li></ul><p><strong>If You Can't Reach Them:</strong></p><ul><li>Try multiple methods (call, text, email)</li><li>Contact emergency contact with consent</li><li>Document attempts to reach</li><li>Consider welfare check if concerns persist</li></ul>" },
          { title: "Short-Term Follow-Up (1-4 weeks)", content: "<p>During this period, focus on stabilization and beginning to address underlying issues.</p><p><strong>Session Frequency:</strong></p><ul><li>Increase session frequency if clinically indicated</li><li>Weekly or twice-weekly sessions may be appropriate</li><li>Don't reduce frequency too quickly</li></ul><p><strong>Session Content:</strong></p><ul><li><strong>Process the crisis:</strong> What happened? What triggered it? What did they learn?</li><li><strong>Identify triggers:</strong> What situations, thoughts, or emotions led to the crisis?</li><li><strong>Strengthen coping:</strong> What worked? What didn't? What can be added?</li><li><strong>Update safety plan:</strong> Revise based on what was learned</li><li><strong>Address underlying issues:</strong> Begin to work on the problems that contributed to crisis</li></ul><p><strong>Warning Signs of Decompensation:</strong></p><ul><li>Missed appointments without contact</li><li>Return of warning signs identified in safety plan</li><li>New stressors or losses</li><li>Hopelessness returning or deepening</li><li>Withdrawal from supports</li></ul>" },
          { title: "Caring Contacts: Evidence-Based Outreach", content: "<p><strong>Caring contacts</strong> are brief, non-demanding outreach to clients after crisis. Research shows they significantly reduce suicide attempts and are one of the most cost-effective interventions we have.</p><p><strong>What Makes Them Effective:</strong></p><ul><li>They communicate 'I'm thinking of you' without demands</li><li>They maintain connection during vulnerable periods</li><li>They remind the person someone cares</li><li>They're low-burden for both clinician and client</li></ul><p><strong>What They Look Like:</strong></p><ul><li>A brief phone call: 'Hi, I've been thinking of you and wanted to check in. How are you doing?'</li><li>A text message: 'Just wanted you to know I'm here if you need anything.'</li><li>A brief card or letter: 'I hope you're doing well. I'm here if you need support.'</li></ul><p><strong>Key Elements:</strong></p><ul><li>Express genuine care and concern</li><li>No demands or expectations</li><li>Remind them of resources available</li><li>Keep the door open for contact</li><li>Brief—not a therapy session</li></ul><p><strong>Timing:</strong></p><ul><li>Days 1, 3, 7 after crisis</li><li>Then weekly for the first month</li><li>Then monthly for several months</li><li>Adjust based on risk level and clinical judgment</li></ul>" },
          { title: "Documentation Requirements", content: "<p>Thorough documentation of crisis intervention and follow-up is essential for continuity of care and legal protection.</p><p><strong>Document for Every Crisis Contact:</strong></p><ul><li><strong>Risk assessment findings:</strong> Specific risk and protective factors identified</li><li><strong>Risk level determination:</strong> Low, moderate, high, imminent—AND your rationale</li><li><strong>Interventions implemented:</strong> What you did and why</li><li><strong>Safety plan:</strong> Whether created, reviewed, or updated (include copy or summary)</li><li><strong>Means restriction:</strong> Discussion about lethal means and actions taken</li><li><strong>Consultations:</strong> Who you consulted and recommendations received</li><li><strong>Follow-up plan:</strong> Specific next steps with timeline</li><li><strong>Client response:</strong> How client responded to interventions, agreements made</li></ul><p><strong>Document Your Reasoning:</strong></p><ul><li>Why you determined the risk level you did</li><li>Why you chose the interventions you did</li><li>Why hospitalization was or wasn't recommended</li><li>If client declined recommendations, document this and their reasoning</li></ul><p><strong>Remember:</strong> Documentation protects the client through continuity of care AND protects you by demonstrating standard of care. Be thorough but factual.</p>" },
          { title: "Clinician Self-Care: Taking Care of the Caregiver", content: "<p>Working with clients in crisis is emotionally and physically taxing. Clinician self-care isn't selfish—it's professionally necessary and ethically required.</p><p><strong>Immediate Post-Crisis Care:</strong></p><ul><li><strong>Debrief:</strong> Talk with a colleague or supervisor about the case</li><li><strong>Acknowledge your feelings:</strong> It's normal to feel scared, sad, exhausted, or even angry</li><li><strong>Take a break:</strong> If possible, take even 10-15 minutes before your next client</li><li><strong>Move your body:</strong> Walk, stretch, shake off the physical tension</li><li><strong>Ground yourself:</strong> Use the same techniques you teach clients</li></ul><p><strong>Ongoing Self-Care:</strong></p><ul><li>Limit crisis-intensive caseload when possible</li><li>Ensure regular supervision/consultation</li><li>Maintain boundaries between work and personal life</li><li>Attend to sleep, nutrition, exercise</li><li>Cultivate relationships and activities outside work</li><li>Consider your own therapy</li></ul><p><strong>Signs of Burnout or Vicarious Trauma:</strong></p><ul><li>Dreading going to work</li><li>Emotional numbing or detachment</li><li>Intrusive thoughts about clients</li><li>Physical symptoms (headaches, sleep problems)</li><li>Increased substance use</li><li>Cynicism about the work or clients</li></ul><p><strong>If you notice these signs:</strong> Seek support immediately. Talk to a supervisor, consult with a colleague, or seek your own therapy. You cannot pour from an empty cup.</p>" }
        ]},
        { type: "imageText", order: 4, image: "https://images.unsplash.com/photo-1517048676732-d65bc937f952?w=600", imageAlt: "Follow-up care", imagePosition: "right", title: "Key Takeaways", content: "<ul><li>Crisis intervention is a core clinical skill</li><li>Always ask directly about suicide</li><li>Use evidence-based risk assessment</li><li>Safety plans are collaborative and specific</li><li>De-escalation starts with your own calm</li><li>Follow-up is essential, not optional</li><li>Document thoroughly</li><li>Take care of yourself too</li></ul>", highlight: true },
        { type: "resources", order: 5, title: "Crisis Resources", description: "Download these tools", resources: [
          { title: "Suicide Risk Assessment Guide", type: "checklist", url: "https://res.cloudinary.com/dzfscjhdx/raw/upload/resources/crisis/suicide-risk-assessment.pdf", size: "267 KB" },
          { title: "Post-Crisis Follow-Up Checklist", type: "checklist", url: "https://res.cloudinary.com/dzfscjhdx/raw/upload/resources/crisis/post-crisis-followup.pdf", size: "145 KB" }
        ]},
        { type: "reflection", order: 6, title: "Clinical Reflection: Self-Care After Crisis Work", prompt: "How do you currently take care of yourself after working with a client in crisis? Do you debrief with colleagues? Practice self-care? Or do you tend to push through? What's one thing you could do differently to better support yourself after difficult clinical work?", placeholder: "Reflect on your self-care practices after crisis intervention...", minLength: 100 }
      ],
      hasQuiz: true, quizPassThreshold: 0.8,
      quizQuestions: [
        { question: "Research shows that 'caring contacts' after crisis:", type: "multipleChoice", options: [{ text: "Have no effect on outcomes", isCorrect: false }, { text: "Reduce suicide attempts", isCorrect: true }, { text: "Increase dependency", isCorrect: false }, { text: "Are unethical boundary violations", isCorrect: false }], explanation: "Research shows caring contacts reduce suicide attempts." },
        { question: "The period of highest suicide risk is:", type: "multipleChoice", options: [{ text: "During acute crisis", isCorrect: false }, { text: "Days/weeks after crisis or discharge", isCorrect: true }, { text: "Years after the event", isCorrect: false }, { text: "Before any crisis occurs", isCorrect: false }], explanation: "Suicide risk is elevated in the days and weeks after crisis resolution or psychiatric discharge." }
      ]
    }
  ],
  assessment: {
    title: "Final Assessment: Crisis Intervention",
    description: "This comprehensive assessment evaluates your understanding of crisis theory fundamentals, suicide risk assessment using evidence-based protocols, collaborative safety planning interventions, verbal de-escalation techniques for agitated clients, and essential post-crisis follow-up care. You must score 80% or higher to receive CE credit.",
    timeLimit: 30,
    passThreshold: 0.8,
    attemptsAllowed: 3,
    shuffleQuestions: true,
    shuffleOptions: true,
    questions: [
      { question: "A crisis is typically time-limited, lasting:", type: "multipleChoice", options: [{ text: "24-48 hours", isCorrect: false }, { text: "4-6 weeks", isCorrect: true }, { text: "6-12 months", isCorrect: false }, { text: "Indefinitely", isCorrect: false }], explanation: "Crises typically resolve within 4-6 weeks." },
      { question: "The strongest predictor of future suicide is:", type: "multipleChoice", options: [{ text: "Depression diagnosis", isCorrect: false }, { text: "Family history of mental illness", isCorrect: false }, { text: "Previous suicide attempt", isCorrect: true }, { text: "Substance abuse alone", isCorrect: false }], explanation: "Previous attempt is the strongest predictor." },
      { question: "Asking directly about suicide:", type: "multipleChoice", options: [{ text: "Increases risk by planting ideas", isCorrect: false }, { text: "Should be avoided with depressed clients", isCorrect: false }, { text: "Does NOT increase risk and is essential for assessment", isCorrect: true }, { text: "Is only appropriate for psychiatrists", isCorrect: false }], explanation: "Research consistently shows direct questions do not increase risk." },
      { question: "Safety plans should be:", type: "multipleChoice", options: [{ text: "Written by clinician alone for efficiency", isCorrect: false }, { text: "Collaborative, specific, and in the client's own words", isCorrect: true }, { text: "Kept in clinical file only", isCorrect: false }, { text: "Generic templates used for all clients", isCorrect: false }], explanation: "Safety plans are developed collaboratively with specific details in the client's language." },
      { question: "The most effective suicide prevention strategy is:", type: "multipleChoice", options: [{ text: "No-suicide contracts", isCorrect: false }, { text: "Hospitalization for all suicidal clients", isCorrect: false }, { text: "Means restriction (limiting access to lethal methods)", isCorrect: true }, { text: "Medication alone", isCorrect: false }], explanation: "Means restriction is one of the most effective strategies—studies show it saves lives." },
      { question: "The first step in de-escalation is:", type: "multipleChoice", options: [{ text: "Tell the person to calm down", isCorrect: false }, { text: "Call security immediately", isCorrect: false }, { text: "Regulate yourself first", isCorrect: true }, { text: "Set firm limits and rules", isCorrect: false }], explanation: "Regulate yourself first — your calm is contagious, and you can't de-escalate someone while escalated yourself." },
      { question: "LEAP (Listen, Empathize, Agree, Partner) is a technique for:", type: "multipleChoice", options: [{ text: "Suicide risk assessment", isCorrect: false }, { text: "De-escalation and engagement", isCorrect: true }, { text: "Documentation", isCorrect: false }, { text: "Medication management", isCorrect: false }], explanation: "LEAP is a de-escalation approach that builds rapport while moving toward resolution." },
      { question: "The period of highest suicide risk is:", type: "multipleChoice", options: [{ text: "During the initial crisis", isCorrect: false }, { text: "Days to weeks after crisis resolution or hospital discharge", isCorrect: true }, { text: "Years after the crisis event", isCorrect: false }, { text: "Before any crisis occurs", isCorrect: false }], explanation: "Risk is elevated in the days and weeks after crisis resolution or discharge from care." },
      { question: "Caring contacts after crisis:", type: "multipleChoice", options: [{ text: "Have no effect on outcomes", isCorrect: false }, { text: "Are shown by research to reduce suicide attempts", isCorrect: true }, { text: "Are boundary violations", isCorrect: false }, { text: "Increase client dependency", isCorrect: false }], explanation: "Research shows caring contacts (brief, non-demanding outreach) reduce suicide attempts." },
      { question: "After a crisis intervention, clinicians should:", type: "multipleChoice", options: [{ text: "Move on immediately to the next client", isCorrect: false }, { text: "Debrief, acknowledge their feelings, and practice self-care", isCorrect: true }, { text: "Avoid thinking about the case", isCorrect: false }, { text: "Keep any stress responses to themselves", isCorrect: false }], explanation: "Self-care and debriefing are essential after crisis work to prevent burnout and vicarious trauma." },
      { question: "The 4 P's of suicide assessment include all EXCEPT:", type: "multipleChoice", options: [{ text: "Plan", isCorrect: false }, { text: "Preparation", isCorrect: false }, { text: "Prior attempts", isCorrect: false }, { text: "Personality type", isCorrect: true }], explanation: "The 4 P's are Plan, Preparation, Prior attempts, and Purpose (what they hope to achieve)." },
      { question: "According to Roberts' Seven-Stage Model, the FIRST stage of crisis intervention is:", type: "multipleChoice", options: [{ text: "Establish rapport", isCorrect: false }, { text: "Plan and conduct crisis assessment", isCorrect: true }, { text: "Generate alternatives", isCorrect: false }, { text: "Develop action plan", isCorrect: false }], explanation: "Assessment of lethality and safety needs comes first in Roberts' model." },
      { question: "A client says 'I wish I could just go to sleep and never wake up.' This statement:", type: "multipleChoice", options: [{ text: "Is not concerning because they didn't mention suicide", isCorrect: false }, { text: "Indicates passive suicidal ideation requiring further assessment", isCorrect: true }, { text: "Should be ignored as a figure of speech", isCorrect: false }, { text: "Automatically requires hospitalization", isCorrect: false }], explanation: "This is passive suicidal ideation (death wish) and requires further assessment to determine risk level." },
      { question: "Which is TRUE about no-suicide contracts?", type: "multipleChoice", options: [{ text: "They are highly effective at preventing suicide", isCorrect: false }, { text: "Research shows they are NOT effective and should not replace proper assessment", isCorrect: true }, { text: "They provide legal protection for clinicians", isCorrect: false }, { text: "They are required before discharge from hospital", isCorrect: false }], explanation: "Research shows no-suicide contracts are not effective. Safety planning has replaced this outdated practice." },
      { question: "When de-escalating, you should AVOID:", type: "multipleChoice", options: [{ text: "Using a calm, low tone of voice", isCorrect: false }, { text: "Validating the person's feelings", isCorrect: false }, { text: "Telling the person to 'calm down' or 'relax'", isCorrect: true }, { text: "Offering limited choices", isCorrect: false }], explanation: "Telling someone to 'calm down' is dismissive and often escalates rather than de-escalates the situation." }
    ]
  }
};

const updateCourse = async () => {
  await connectDB();
  try {
    crisisCourse.totalEstimatedTime = crisisCourse.sections.reduce((sum, s) => sum + (s.estimatedTime || 15), 0);
    crisisCourse.totalContentBlocks = crisisCourse.sections.reduce((sum, s) => sum + s.contentBlocks.length, 0);
    crisisCourse.totalQuizQuestions = crisisCourse.sections.reduce((sum, s) => sum + (s.quizQuestions?.length || 0), 0) + (crisisCourse.assessment?.questions?.length || 0);
    
    await mongoose.connection.db.collection('interactivecourses').findOneAndUpdate({ slug: crisisCourse.slug }, { $set: crisisCourse }, { upsert: true });
    await mongoose.connection.db.collection('courses').findOneAndUpdate({ slug: crisisCourse.slug }, { $set: crisisCourse }, { upsert: true });
    
    console.log('✅ Crisis Intervention course updated!');
    console.log('   Sections:', crisisCourse.sections.length);
    console.log('   Content Blocks:', crisisCourse.totalContentBlocks);
  } catch (error) {
    console.error('Error:', error.message);
  }
  process.exit(0);
};

updateCourse();
